package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

type fieldInfo struct {
	Name string
	Type string
}

type structInfo struct {
	Name   string
	Fields []fieldInfo
}

type messageMapping struct {
	Const  string
	Struct string
}

var mappings = []messageMapping{
	{"HI", "HIMess"},
	{"UUID", "UUIDMess"},
	{"CHILDUUIDREQ", "ChildUUIDReq"},
	{"CHILDUUIDRES", "ChildUUIDRes"},
	{"MYINFO", "MyInfo"},
	{"MYMEMO", "MyMemo"},
	{"LISTENREQ", "ListenReq"},
	{"LISTENRES", "ListenRes"},
	{"LISTENSTOP", "ListenStop"},
	{"CONNECTSTART", "ConnectStart"},
	{"CONNECTDONE", "ConnectDone"},
	{"NODECONNINFO", "NodeConnInfo"},
	{"NODEOFFLINE", "NodeOffline"},
	{"NODEREONLINE", "NodeReonline"},
	{"UPSTREAMOFFLINE", "UpstreamOffline"},
	{"UPSTREAMREONLINE", "UpstreamReonline"},
	{"SHUTDOWN", "Shutdown"},
	{"HEARTBEAT", "HeartbeatMsg"},
	{"RUNTIMELOG", "RuntimeLog"},
	{"GOSSIP_UPDATE", "GossipUpdate"},
	{"GOSSIP_REQUEST", "GossipRequest"},
	{"GOSSIP_RESPONSE", "GossipResponse"},
	{"GOSSIP_DISCOVER", "GossipDiscover"},
	{"GOSSIP_HEARTBEAT", "GossipHeartbeat"},
	{"GOSSIP_ROUTE_UPDATE", "GossipRouteUpdate"},
	{"GOSSIP_NODE_JOIN", "GossipNodeJoin"},
	{"GOSSIP_NODE_LEAVE", "GossipNodeLeave"},
	{"SUPPLINKREQ", "SuppLinkRequest"},
	{"SUPPLINKRESP", "SuppLinkResponse"},
	{"SUPPLINKTEARDOWN", "SuppLinkTeardown"},
	{"SUPPLINKHEARTBEAT", "SuppLinkHeartbeat"},
	{"SUPPFAILOVER", "SuppFailoverCommand"},
	{"SUPPLINKPROMOTE", "SuppLinkPromote"},
	{"RESCUE_REQUEST", "RescueRequest"},
	{"RESCUE_RESPONSE", "RescueResponse"},
	{"DTN_DATA", "DTNData"},
	{"DTN_ACK", "DTNAck"},
	{"DTN_PULL", "DTNPull"},
	{"STREAM_OPEN", "StreamOpen"},
	{"STREAM_DATA", "StreamData"},
	{"STREAM_ACK", "StreamAck"},
	{"STREAM_CLOSE", "StreamClose"},
	{"SLEEP_UPDATE", "SleepUpdate"},
	{"SLEEP_UPDATE_ACK", "SleepUpdateAck"},
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gencodec: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	structs, err := parseStructs()
	if err != nil {
		return err
	}

	code, err := generateCodec(structs)
	if err != nil {
		return err
	}
	testCode, err := generateTests(structs)
	if err != nil {
		return err
	}

	outDir := "protocol"
	// `go generate` 运行本工具时的 CWD 是 protocol/，而手工运行通常位于仓库根目录。
	// 这里通过检测当前目录中是否存在 protocol.go 来兼容这两种布局。
	if _, statErr := os.Stat("protocol.go"); statErr == nil {
		outDir = "."
	}

	if err := os.WriteFile(filepath.Join(outDir, "messages_generated.go"), code, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "messages_generated_test.go"), testCode, 0o644); err != nil {
		return err
	}
	return nil
}

func parseStructs() (map[string]structInfo, error) {
	// 优先使用相对于当前目录的路径（go generate 会从 protocol/ 运行），
	// 若找不到再回退到相对于仓库根目录的路径。
	candidateSets := [][]string{
		{"protocol.go", "gossip.go"},
		{filepath.Join("protocol", "protocol.go"), filepath.Join("protocol", "gossip.go")},
	}
	var files []string
	for _, set := range candidateSets {
		ok := true
		for _, f := range set {
			if _, err := os.Stat(f); err != nil {
				ok = false
				break
			}
		}
		if ok {
			files = set
			break
		}
	}
	if files == nil {
		return nil, fmt.Errorf("unable to locate protocol struct definitions (expected protocol.go + gossip.go)")
	}
	fset := token.NewFileSet()
	result := make(map[string]structInfo)
	for _, file := range files {
		astFile, err := parser.ParseFile(fset, file, nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, err
		}
		for _, decl := range astFile.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}
				fields := make([]fieldInfo, 0, len(structType.Fields.List))
				for _, field := range structType.Fields.List {
					if len(field.Names) == 0 {
						continue
					}
					name := field.Names[0].Name
					ftype := exprString(fset, field.Type)
					fields = append(fields, fieldInfo{Name: name, Type: ftype})
				}
				result[typeSpec.Name.Name] = structInfo{
					Name:   typeSpec.Name.Name,
					Fields: fields,
				}
			}
		}
	}
	return result, nil
}

func exprString(fset *token.FileSet, expr ast.Expr) string {
	var buf bytes.Buffer
	printer.Fprint(&buf, fset, expr)
	return buf.String()
}

func generateCodec(structs map[string]structInfo) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gencodec; DO NOT EDIT.\n")
	buf.WriteString("package protocol\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"encoding/binary\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString(helperFunctions)

	// 为每个结构体生成序列化 / 反序列化方法
	for _, mapping := range mappings {
		info, ok := structs[mapping.Struct]
		if !ok {
			return nil, fmt.Errorf("struct %s not found", mapping.Struct)
		}
		if err := writeMarshal(&buf, info); err != nil {
			return nil, err
		}
		if err := writeUnmarshal(&buf, info); err != nil {
			return nil, err
		}
	}

	// 生成 MarshalMessage 的分发逻辑
	if err := writeMarshalMessage(&buf); err != nil {
		return nil, err
	}
	if err := writeUnmarshalMessage(&buf); err != nil {
		return nil, err
	}

	return formatSource(buf.Bytes())
}

func writeMarshal(buf *bytes.Buffer, info structInfo) error {
	funcName := "marshal" + info.Name
	fmt.Fprintf(buf, "func %s(msg *%s) ([]byte, error) {\n", funcName, info.Name)
	fmt.Fprintf(buf, "\tif msg == nil {\n\t\treturn nil, fmt.Errorf(\"codec: nil %s\")\n\t}\n", info.Name)
	fmt.Fprintf(buf, "\tbuf := make([]byte, 0)\n")
	for i := 0; i < len(info.Fields); i++ {
		field := info.Fields[i]
		if strings.HasSuffix(field.Name, "Len") && i+1 < len(info.Fields) {
			next := info.Fields[i+1]
			prefix := strings.TrimSuffix(field.Name, "Len")
			if strings.HasPrefix(next.Name, prefix) {
				switch field.Type {
				case "uint16", "uint32", "uint64":
					fmt.Fprintf(buf, "\tmsg.%s = %s(len(msg.%s))\n", field.Name, field.Type, next.Name)
				}
			}
		}
		writeMarshalField(buf, info.Name, field)
	}
	fmt.Fprintf(buf, "\treturn buf, nil\n}\n\n")
	return nil
}

func writeMarshalField(buf *bytes.Buffer, structName string, field fieldInfo) {
	name := fmt.Sprintf("msg.%s", field.Name)
	switch field.Type {
	case "string":
		fmt.Fprintf(buf, "\tbuf = append(buf, []byte(%s)...)\n", name)
	case "[]byte":
		fmt.Fprintf(buf, "\tbuf = append(buf, %s...)\n", name)
	case "uint16":
		fmt.Fprintf(buf, "\tbuf = appendUint16(buf, %s)\n", name)
	case "uint32":
		fmt.Fprintf(buf, "\tbuf = appendUint32(buf, %s)\n", name)
	case "uint64":
		fmt.Fprintf(buf, "\tbuf = appendUint64(buf, %s)\n", name)
	case "int32":
		fmt.Fprintf(buf, "\tbuf = appendInt32(buf, %s)\n", name)
	case "int64":
		fmt.Fprintf(buf, "\tbuf = appendInt64(buf, %s)\n", name)
	case "uint8":
		fmt.Fprintf(buf, "\tbuf = append(buf, byte(%s))\n", name)
	case "bool":
		fmt.Fprintf(buf, "\tbuf = appendBool(buf, %s)\n", name)
	default:
		fmt.Fprintf(buf, "\t// 不支持的字段类型 %s.%s (%s)\n", structName, field.Name, field.Type)
	}
}

func writeUnmarshal(buf *bytes.Buffer, info structInfo) error {
	funcName := "unmarshal" + info.Name
	fmt.Fprintf(buf, "func %s(data []byte) (*%s, error) {\n", funcName, info.Name)
	fmt.Fprintf(buf, "\tmsg := &%s{}\n", info.Name)
	for idx, field := range info.Fields {
		if strings.HasSuffix(field.Name, "Len") {
			if writeLengthField(buf, info, idx) {
				continue
			}
		}
		writeUnmarshalField(buf, info, field)
	}
	fmt.Fprintf(buf, "\t_ = data\n\treturn msg, nil\n}\n\n")
	return nil
}

func writeLengthField(buf *bytes.Buffer, info structInfo, index int) bool {
	field := info.Fields[index]
	if index+1 >= len(info.Fields) {
		return false
	}
	next := info.Fields[index+1]
	prefix := strings.TrimSuffix(field.Name, "Len")
	if !strings.HasPrefix(next.Name, prefix) {
		return false
	}
	name := fmt.Sprintf("msg.%s", field.Name)
	switch field.Type {
	case "uint16":
		fmt.Fprintf(buf, "\tif len(data) < 2 {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s overflow\")\n\t}\n", info.Name, field.Name)
		fmt.Fprintf(buf, "\t%s = binary.BigEndian.Uint16(data[:2])\n", name)
		fmt.Fprintf(buf, "\tdata = data[2:]\n")
	case "uint32":
		fmt.Fprintf(buf, "\tif len(data) < 4 {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s overflow\")\n\t}\n", info.Name, field.Name)
		fmt.Fprintf(buf, "\t%s = binary.BigEndian.Uint32(data[:4])\n", name)
		fmt.Fprintf(buf, "\tdata = data[4:]\n")
	case "uint64":
		fmt.Fprintf(buf, "\tif len(data) < 8 {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s overflow\")\n\t}\n", info.Name, field.Name)
		fmt.Fprintf(buf, "\t%s = binary.BigEndian.Uint64(data[:8])\n", name)
		fmt.Fprintf(buf, "\tdata = data[8:]\n")
	default:
		return false
	}
	return true
}

func writeUnmarshalField(buf *bytes.Buffer, info structInfo, field fieldInfo) {
	name := fmt.Sprintf("msg.%s", field.Name)
	switch field.Type {
	case "string":
		lenField := findLenField(info.Fields, field.Name)
		if lenField == nil {
			fmt.Fprintf(buf, "\tif len(data) < 0 {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s invalid length\")\n\t}\n", info.Name, field.Name)
			fmt.Fprintf(buf, "\t%s = string(data)\n\tdata = data[:0]\n", name)
			return
		}
		lengthExpr := lengthCast(fmt.Sprintf("msg.%s", lenField.Name), lenField.Type)
		fmt.Fprintf(buf, "\tif %s > uint64(len(data)) {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s overflow\")\n\t}\n", lengthExpr, info.Name, field.Name)
		fmt.Fprintf(buf, "\t%s = string(data[:%s])\n", name, lengthExpr)
		fmt.Fprintf(buf, "\tdata = data[%s:]\n", lengthExpr)
	case "[]byte":
		lenField := findLenField(info.Fields, field.Name)
		if lenField == nil {
			fmt.Fprintf(buf, "\tif len(data) < 0 {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s invalid length\")\n\t}\n", info.Name, field.Name)
			fmt.Fprintf(buf, "\t%s = append([]byte(nil), data...)\n\tdata = data[:0]\n", name)
			return
		}
		lengthExpr := lengthCast(fmt.Sprintf("msg.%s", lenField.Name), lenField.Type)
		fmt.Fprintf(buf, "\tif %s > uint64(len(data)) {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s overflow\")\n\t}\n", lengthExpr, info.Name, field.Name)
		fmt.Fprintf(buf, "\t%s = append([]byte(nil), data[:%s]...)\n", name, lengthExpr)
		fmt.Fprintf(buf, "\tdata = data[%s:]\n", lengthExpr)
	case "uint16":
		fmt.Fprintf(buf, "\tif len(data) < 2 {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s overflow\")\n\t}\n", info.Name, field.Name)
		fmt.Fprintf(buf, "\t%s = binary.BigEndian.Uint16(data[:2])\n", name)
		fmt.Fprintf(buf, "\tdata = data[2:]\n")
	case "uint32":
		fmt.Fprintf(buf, "\tif len(data) < 4 {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s overflow\")\n\t}\n", info.Name, field.Name)
		fmt.Fprintf(buf, "\t%s = binary.BigEndian.Uint32(data[:4])\n", name)
		fmt.Fprintf(buf, "\tdata = data[4:]\n")
	case "uint64":
		fmt.Fprintf(buf, "\tif len(data) < 8 {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s overflow\")\n\t}\n", info.Name, field.Name)
		fmt.Fprintf(buf, "\t%s = binary.BigEndian.Uint64(data[:8])\n", name)
		fmt.Fprintf(buf, "\tdata = data[8:]\n")
	case "int32":
		fmt.Fprintf(buf, "\tif len(data) < 4 {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s overflow\")\n\t}\n", info.Name, field.Name)
		fmt.Fprintf(buf, "\t%s = int32(binary.BigEndian.Uint32(data[:4]))\n", name)
		fmt.Fprintf(buf, "\tdata = data[4:]\n")
	case "int64":
		fmt.Fprintf(buf, "\tif len(data) < 8 {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s overflow\")\n\t}\n", info.Name, field.Name)
		fmt.Fprintf(buf, "\t%s = int64(binary.BigEndian.Uint64(data[:8]))\n", name)
		fmt.Fprintf(buf, "\tdata = data[8:]\n")
	case "uint8":
		fmt.Fprintf(buf, "\tif len(data) < 1 {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s overflow\")\n\t}\n", info.Name, field.Name)
		fmt.Fprintf(buf, "\t%s = uint8(data[0])\n", name)
		fmt.Fprintf(buf, "\tdata = data[1:]\n")
	case "bool":
		fmt.Fprintf(buf, "\tif len(data) < 1 {\n\t\treturn nil, fmt.Errorf(\"codec: %s.%s overflow\")\n\t}\n", info.Name, field.Name)
		fmt.Fprintf(buf, "\t%s = data[0] != 0\n", name)
		fmt.Fprintf(buf, "\tdata = data[1:]\n")
	default:
		fmt.Fprintf(buf, "\t// 不支持的字段类型 %s.%s (%s)\n", info.Name, field.Name, field.Type)
	}
}

func findLenField(fields []fieldInfo, fieldName string) *fieldInfo {
	target := fieldName + "Len"
	for i := range fields {
		if fields[i].Name == target {
			return &fields[i]
		}
	}
	for i := range fields {
		if !strings.HasSuffix(fields[i].Name, "Len") {
			continue
		}
		prefix := strings.TrimSuffix(fields[i].Name, "Len")
		if strings.HasPrefix(fieldName, prefix) {
			return &fields[i]
		}
	}
	return nil
}

func lengthCast(name, fieldType string) string {
	switch fieldType {
	case "uint16":
		return fmt.Sprintf("uint64(%s)", name)
	case "uint32":
		return fmt.Sprintf("uint64(%s)", name)
	case "uint64":
		return name
	default:
		return fmt.Sprintf("uint64(%s)", name)
	}
}

func writeMarshalMessage(buf *bytes.Buffer) error {
	buf.WriteString("func marshalMessagePayload(msg interface{}) ([]byte, error) {\n")
	buf.WriteString("\tswitch m := msg.(type) {\n")
	for _, mapping := range mappings {
		fmt.Fprintf(buf, "\tcase *%s:\n", mapping.Struct)
		fmt.Fprintf(buf, "\t\treturn marshal%s(m)\n", mapping.Struct)
	}
	buf.WriteString("\tdefault:\n")
	buf.WriteString("\t\treturn nil, fmt.Errorf(\"codec: unsupported message %T\", msg)\n")
	buf.WriteString("\t}\n}\n\n")
	return nil
}

func writeUnmarshalMessage(buf *bytes.Buffer) error {
	buf.WriteString("func unmarshalMessagePayload(messageType uint16, data []byte) (interface{}, error) {\n")
	buf.WriteString("\tswitch messageType {\n")
	for _, mapping := range mappings {
		fmt.Fprintf(buf, "\tcase %s:\n", mapping.Const)
		fmt.Fprintf(buf, "\t\treturn unmarshal%s(data)\n", mapping.Struct)
	}
	buf.WriteString("\tdefault:\n")
	buf.WriteString("\t\treturn nil, fmt.Errorf(\"codec: unsupported message type %d\", messageType)\n")
	buf.WriteString("\t}\n}\n\n")
	return nil
}

func generateTests(structs map[string]structInfo) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gencodec; DO NOT EDIT.\n")
	buf.WriteString("package protocol\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"reflect\"\n")
	buf.WriteString("\t\"testing\"\n")
	buf.WriteString(")\n\n")

	for _, mapping := range mappings {
		info := structs[mapping.Struct]
		writeSampleBuilder(&buf, info)
	}

	buf.WriteString("func TestMessageCodecRoundTrip(t *testing.T) {\n")
	buf.WriteString("\ttests := []struct {\n")
	buf.WriteString("\t\tname string\n")
	buf.WriteString("\t\tconstructor func() interface{}\n")
	buf.WriteString("\t}{}\n")

	for _, mapping := range mappings {
		info := structs[mapping.Struct]
		fmt.Fprintf(&buf, "\ttests = append(tests, struct {\n")
		buf.WriteString("\t\tname string\n")
		buf.WriteString("\t\tconstructor func() interface{}\n")
		buf.WriteString("\t}{\n")
		fmt.Fprintf(&buf, "\t\tname: \"%s\",\n", mapping.Struct)
		fmt.Fprintf(&buf, "\t\tconstructor: func() interface{} { return %s() },\n", sampleFuncName(info.Name))
		buf.WriteString("\t})\n")
	}

	buf.WriteString("\tfor _, tt := range tests {\n")
	buf.WriteString("\t\tt.Run(tt.name, func(t *testing.T) {\n")
	buf.WriteString("\t\t\tmsg := tt.constructor()\n")
	buf.WriteString("\t\t\tdata, err := marshalMessagePayload(msg)\n")
	buf.WriteString("\t\t\tif err != nil {\n\t\t\t\tt.Fatalf(\"marshal failed: %v\", err)\n\t\t\t}\n")
	buf.WriteString("\t\t\tdecoded, err := unmarshalMessagePayload(messageTypeFor(msg), data)\n")
	buf.WriteString("\t\t\tif err != nil {\n\t\t\t\tt.Fatalf(\"unmarshal failed: %v\", err)\n\t\t\t}\n")
	buf.WriteString("\t\t\tif !reflect.DeepEqual(msg, decoded) {\n")
	buf.WriteString("\t\t\t\tt.Fatalf(\"round trip mismatch: %v vs %v\", msg, decoded)\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t})\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// 生成 messageTypeFor 辅助映射
	buf.WriteString("func messageTypeFor(msg interface{}) uint16 {\n")
	buf.WriteString("\tswitch msg.(type) {\n")
	for _, mapping := range mappings {
		fmt.Fprintf(&buf, "\tcase *%s:\n", mapping.Struct)
		fmt.Fprintf(&buf, "\t\treturn %s\n", mapping.Const)
	}
	buf.WriteString("\tdefault:\n\t\treturn 0\n\t}\n}\n")

	return formatSource(buf.Bytes())
}

func sampleFuncName(structName string) string {
	return "newSample" + structName
}

func writeSampleBuilder(buf *bytes.Buffer, info structInfo) {
	fmt.Fprintf(buf, "func %s() interface{} {\n", sampleFuncName(info.Name))
	fmt.Fprintf(buf, "\tmsg := &%s{}\n", info.Name)
	for i, field := range info.Fields {
		if strings.HasSuffix(field.Name, "Len") {
			if i+1 < len(info.Fields) {
				next := info.Fields[i+1]
				if strings.HasPrefix(next.Name, strings.TrimSuffix(field.Name, "Len")) {
					continue
				}
			}
		}
		writeSampleField(buf, info, field)
	}
	fmt.Fprintf(buf, "\treturn msg\n}\n\n")
}

func writeSampleField(buf *bytes.Buffer, info structInfo, field fieldInfo) {
	name := fmt.Sprintf("msg.%s", field.Name)
	switch field.Type {
	case "string":
		value := fmt.Sprintf("%s-value", strings.ToLower(field.Name))
		fmt.Fprintf(buf, "\t%s = \"%s\"\n", name, value)
		if lenField := findLenField(info.Fields, field.Name); lenField != nil {
			fmt.Fprintf(buf, "\tmsg.%s = %s(len(%s))\n", lenField.Name, lenField.Type, name)
		}
	case "[]byte":
		fmt.Fprintf(buf, "\t%s = []byte{0x01, 0x02, 0x03}\n", name)
		if lenField := findLenField(info.Fields, field.Name); lenField != nil {
			fmt.Fprintf(buf, "\tmsg.%s = %s(len(%s))\n", lenField.Name, lenField.Type, name)
		}
	case "uint16":
		fmt.Fprintf(buf, "\t%s = 1\n", name)
	case "uint32":
		fmt.Fprintf(buf, "\t%s = 2\n", name)
	case "uint64":
		fmt.Fprintf(buf, "\t%s = 3\n", name)
	case "int32":
		fmt.Fprintf(buf, "\t%s = int32(4)\n", name)
	case "int64":
		fmt.Fprintf(buf, "\t%s = int64(5)\n", name)
	case "bool":
		fmt.Fprintf(buf, "\t%s = true\n", name)
	case "uint8":
		fmt.Fprintf(buf, "\t%s = 1\n", name)
	default:
		fmt.Fprintf(buf, "\t// 未定义 %s.%s 的示例值 (%s)\n", info.Name, field.Name, field.Type)
	}
}

func formatSource(src []byte) ([]byte, error) {
	return format.Source(src)
}

const helperFunctions = `
func appendUint16(buf []byte, v uint16) []byte {
	var tmp [2]byte
	binary.BigEndian.PutUint16(tmp[:], v)
	return append(buf, tmp[:]...)
}

func appendUint32(buf []byte, v uint32) []byte {
	var tmp [4]byte
	binary.BigEndian.PutUint32(tmp[:], v)
	return append(buf, tmp[:]...)
}

func appendUint64(buf []byte, v uint64) []byte {
	var tmp [8]byte
	binary.BigEndian.PutUint64(tmp[:], v)
	return append(buf, tmp[:]...)
}

func appendInt32(buf []byte, v int32) []byte {
	return appendUint32(buf, uint32(v))
}

func appendInt64(buf []byte, v int64) []byte {
	return appendUint64(buf, uint64(v))
}

func appendBool(buf []byte, v bool) []byte {
	if v {
		return append(buf, 1)
	}
	return append(buf, 0)
}
`
