// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/dataplane/v1/dataplane.proto

package dataplanepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DataplaneAdmin_PrepareTransfer_FullMethodName  = "/dataplane.v1.DataplaneAdmin/PrepareTransfer"
	DataplaneAdmin_CompleteTransfer_FullMethodName = "/dataplane.v1.DataplaneAdmin/CompleteTransfer"
	DataplaneAdmin_PrepareProxy_FullMethodName     = "/dataplane.v1.DataplaneAdmin/PrepareProxy"
	DataplaneAdmin_CompleteProxy_FullMethodName    = "/dataplane.v1.DataplaneAdmin/CompleteProxy"
)

// DataplaneAdminClient is the client API for DataplaneAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataplaneAdminClient interface {
	PrepareTransfer(ctx context.Context, in *PrepareTransferRequest, opts ...grpc.CallOption) (*PrepareTransferResponse, error)
	CompleteTransfer(ctx context.Context, in *CompleteTransferRequest, opts ...grpc.CallOption) (*CompleteTransferResponse, error)
	PrepareProxy(ctx context.Context, in *PrepareProxyRequest, opts ...grpc.CallOption) (*PrepareProxyResponse, error)
	CompleteProxy(ctx context.Context, in *CompleteProxyRequest, opts ...grpc.CallOption) (*CompleteProxyResponse, error)
}

type dataplaneAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewDataplaneAdminClient(cc grpc.ClientConnInterface) DataplaneAdminClient {
	return &dataplaneAdminClient{cc}
}

func (c *dataplaneAdminClient) PrepareTransfer(ctx context.Context, in *PrepareTransferRequest, opts ...grpc.CallOption) (*PrepareTransferResponse, error) {
	out := new(PrepareTransferResponse)
	err := c.cc.Invoke(ctx, DataplaneAdmin_PrepareTransfer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneAdminClient) CompleteTransfer(ctx context.Context, in *CompleteTransferRequest, opts ...grpc.CallOption) (*CompleteTransferResponse, error) {
	out := new(CompleteTransferResponse)
	err := c.cc.Invoke(ctx, DataplaneAdmin_CompleteTransfer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneAdminClient) PrepareProxy(ctx context.Context, in *PrepareProxyRequest, opts ...grpc.CallOption) (*PrepareProxyResponse, error) {
	out := new(PrepareProxyResponse)
	err := c.cc.Invoke(ctx, DataplaneAdmin_PrepareProxy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneAdminClient) CompleteProxy(ctx context.Context, in *CompleteProxyRequest, opts ...grpc.CallOption) (*CompleteProxyResponse, error) {
	out := new(CompleteProxyResponse)
	err := c.cc.Invoke(ctx, DataplaneAdmin_CompleteProxy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataplaneAdminServer is the server API for DataplaneAdmin service.
// All implementations must embed UnimplementedDataplaneAdminServer
// for forward compatibility
type DataplaneAdminServer interface {
	PrepareTransfer(context.Context, *PrepareTransferRequest) (*PrepareTransferResponse, error)
	CompleteTransfer(context.Context, *CompleteTransferRequest) (*CompleteTransferResponse, error)
	PrepareProxy(context.Context, *PrepareProxyRequest) (*PrepareProxyResponse, error)
	CompleteProxy(context.Context, *CompleteProxyRequest) (*CompleteProxyResponse, error)
	mustEmbedUnimplementedDataplaneAdminServer()
}

// UnimplementedDataplaneAdminServer must be embedded to have forward compatible implementations.
type UnimplementedDataplaneAdminServer struct {
}

func (UnimplementedDataplaneAdminServer) PrepareTransfer(context.Context, *PrepareTransferRequest) (*PrepareTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareTransfer not implemented")
}
func (UnimplementedDataplaneAdminServer) CompleteTransfer(context.Context, *CompleteTransferRequest) (*CompleteTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteTransfer not implemented")
}
func (UnimplementedDataplaneAdminServer) PrepareProxy(context.Context, *PrepareProxyRequest) (*PrepareProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareProxy not implemented")
}
func (UnimplementedDataplaneAdminServer) CompleteProxy(context.Context, *CompleteProxyRequest) (*CompleteProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteProxy not implemented")
}
func (UnimplementedDataplaneAdminServer) mustEmbedUnimplementedDataplaneAdminServer() {}

// UnsafeDataplaneAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataplaneAdminServer will
// result in compilation errors.
type UnsafeDataplaneAdminServer interface {
	mustEmbedUnimplementedDataplaneAdminServer()
}

func RegisterDataplaneAdminServer(s grpc.ServiceRegistrar, srv DataplaneAdminServer) {
	s.RegisterService(&DataplaneAdmin_ServiceDesc, srv)
}

func _DataplaneAdmin_PrepareTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneAdminServer).PrepareTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneAdmin_PrepareTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneAdminServer).PrepareTransfer(ctx, req.(*PrepareTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneAdmin_CompleteTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneAdminServer).CompleteTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneAdmin_CompleteTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneAdminServer).CompleteTransfer(ctx, req.(*CompleteTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneAdmin_PrepareProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneAdminServer).PrepareProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneAdmin_PrepareProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneAdminServer).PrepareProxy(ctx, req.(*PrepareProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneAdmin_CompleteProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneAdminServer).CompleteProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneAdmin_CompleteProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneAdminServer).CompleteProxy(ctx, req.(*CompleteProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataplaneAdmin_ServiceDesc is the grpc.ServiceDesc for DataplaneAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataplaneAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataplane.v1.DataplaneAdmin",
	HandlerType: (*DataplaneAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareTransfer",
			Handler:    _DataplaneAdmin_PrepareTransfer_Handler,
		},
		{
			MethodName: "CompleteTransfer",
			Handler:    _DataplaneAdmin_CompleteTransfer_Handler,
		},
		{
			MethodName: "PrepareProxy",
			Handler:    _DataplaneAdmin_PrepareProxy_Handler,
		},
		{
			MethodName: "CompleteProxy",
			Handler:    _DataplaneAdmin_CompleteProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dataplane/v1/dataplane.proto",
}
