// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * Event 是"Kelpie WatchEvents → 前端时间线"所需要的扁平事件结构。
 * 字段只保留在答辩演示中会用到的部分，保持 JSON 序列化短小。
 */
export class Event {
    "seq": number;
    "kind": EventKind;
    "action": string;
    "timestamp": time$0.Time;
    "summary": string;
    "target"?: string;
    "source"?: string;
    "level"?: string;
    "reason"?: string;
    "extras"?: { [_ in string]?: string };

    /** Creates a new Event instance. */
    constructor($$source: Partial<Event> = {}) {
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = EventKind.$zero;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     */
    static createFrom($$source: any = {}): Event {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extras" in $$parsedSource) {
            $$parsedSource["extras"] = $$createField9_0($$parsedSource["extras"]);
        }
        return new Event($$parsedSource as Partial<Event>);
    }
}

/**
 * EventKind 描述一条标准化后的 UI 事件类别。
 * 客户端不直接使用 protobuf oneof，改用该枚举 + 扁平字段，便于 JSON 传给前端。
 */
export enum EventKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EventKindNode = "node",
    EventKindLog = "log",
    EventKindStream = "stream",
    EventKindListener = "listener",
    EventKindSession = "session",
    EventKindDial = "dial",
    EventKindProxy = "proxy",
    EventKindSleep = "sleep",
    EventKindSupplemental = "supplemental",
    EventKindChat = "chat",
    EventKindAudit = "audit",
    EventKindLoot = "loot",
    EventKindUnknown = "unknown",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
