// Code generated by gencodec; DO NOT EDIT.
package protocol

import (
	"encoding/binary"
	"fmt"
)

func appendUint16(buf []byte, v uint16) []byte {
	var tmp [2]byte
	binary.BigEndian.PutUint16(tmp[:], v)
	return append(buf, tmp[:]...)
}

func appendUint32(buf []byte, v uint32) []byte {
	var tmp [4]byte
	binary.BigEndian.PutUint32(tmp[:], v)
	return append(buf, tmp[:]...)
}

func appendUint64(buf []byte, v uint64) []byte {
	var tmp [8]byte
	binary.BigEndian.PutUint64(tmp[:], v)
	return append(buf, tmp[:]...)
}

func appendInt32(buf []byte, v int32) []byte {
	return appendUint32(buf, uint32(v))
}

func appendInt64(buf []byte, v int64) []byte {
	return appendUint64(buf, uint64(v))
}

func appendBool(buf []byte, v bool) []byte {
	if v {
		return append(buf, 1)
	}
	return append(buf, 0)
}
func marshalHIMess(msg *HIMess) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil HIMess")
	}
	buf := make([]byte, 0)
	msg.GreetingLen = uint16(len(msg.Greeting))
	buf = appendUint16(buf, msg.GreetingLen)
	buf = append(buf, []byte(msg.Greeting)...)
	msg.UUIDLen = uint16(len(msg.UUID))
	buf = appendUint16(buf, msg.UUIDLen)
	buf = append(buf, []byte(msg.UUID)...)
	buf = appendUint16(buf, msg.IsAdmin)
	buf = appendUint16(buf, msg.IsReconnect)
	buf = appendUint16(buf, msg.ProtoVersion)
	buf = appendUint16(buf, msg.ProtoFlags)
	return buf, nil
}

func unmarshalHIMess(data []byte) (*HIMess, error) {
	msg := &HIMess{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: HIMess.GreetingLen overflow")
	}
	msg.GreetingLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.GreetingLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: HIMess.Greeting overflow")
	}
	msg.Greeting = string(data[:uint64(msg.GreetingLen)])
	data = data[uint64(msg.GreetingLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: HIMess.UUIDLen overflow")
	}
	msg.UUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.UUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: HIMess.UUID overflow")
	}
	msg.UUID = string(data[:uint64(msg.UUIDLen)])
	data = data[uint64(msg.UUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: HIMess.IsAdmin overflow")
	}
	msg.IsAdmin = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: HIMess.IsReconnect overflow")
	}
	msg.IsReconnect = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: HIMess.ProtoVersion overflow")
	}
	msg.ProtoVersion = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: HIMess.ProtoFlags overflow")
	}
	msg.ProtoFlags = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalUUIDMess(msg *UUIDMess) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil UUIDMess")
	}
	buf := make([]byte, 0)
	msg.UUIDLen = uint16(len(msg.UUID))
	buf = appendUint16(buf, msg.UUIDLen)
	buf = append(buf, []byte(msg.UUID)...)
	buf = appendUint16(buf, msg.ProtoVersion)
	buf = appendUint16(buf, msg.ProtoFlags)
	return buf, nil
}

func unmarshalUUIDMess(data []byte) (*UUIDMess, error) {
	msg := &UUIDMess{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: UUIDMess.UUIDLen overflow")
	}
	msg.UUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.UUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: UUIDMess.UUID overflow")
	}
	msg.UUID = string(data[:uint64(msg.UUIDLen)])
	data = data[uint64(msg.UUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: UUIDMess.ProtoVersion overflow")
	}
	msg.ProtoVersion = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: UUIDMess.ProtoFlags overflow")
	}
	msg.ProtoFlags = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalChildUUIDReq(msg *ChildUUIDReq) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil ChildUUIDReq")
	}
	buf := make([]byte, 0)
	msg.ParentUUIDLen = uint16(len(msg.ParentUUID))
	buf = appendUint16(buf, msg.ParentUUIDLen)
	buf = append(buf, []byte(msg.ParentUUID)...)
	msg.IPLen = uint16(len(msg.IP))
	buf = appendUint16(buf, msg.IPLen)
	buf = append(buf, []byte(msg.IP)...)
	msg.RequestIDLen = uint16(len(msg.RequestID))
	buf = appendUint16(buf, msg.RequestIDLen)
	buf = append(buf, []byte(msg.RequestID)...)
	return buf, nil
}

func unmarshalChildUUIDReq(data []byte) (*ChildUUIDReq, error) {
	msg := &ChildUUIDReq{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: ChildUUIDReq.ParentUUIDLen overflow")
	}
	msg.ParentUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ParentUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: ChildUUIDReq.ParentUUID overflow")
	}
	msg.ParentUUID = string(data[:uint64(msg.ParentUUIDLen)])
	data = data[uint64(msg.ParentUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: ChildUUIDReq.IPLen overflow")
	}
	msg.IPLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.IPLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: ChildUUIDReq.IP overflow")
	}
	msg.IP = string(data[:uint64(msg.IPLen)])
	data = data[uint64(msg.IPLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: ChildUUIDReq.RequestIDLen overflow")
	}
	msg.RequestIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.RequestIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: ChildUUIDReq.RequestID overflow")
	}
	msg.RequestID = string(data[:uint64(msg.RequestIDLen)])
	data = data[uint64(msg.RequestIDLen):]
	_ = data
	return msg, nil
}

func marshalChildUUIDRes(msg *ChildUUIDRes) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil ChildUUIDRes")
	}
	buf := make([]byte, 0)
	msg.UUIDLen = uint16(len(msg.UUID))
	buf = appendUint16(buf, msg.UUIDLen)
	buf = append(buf, []byte(msg.UUID)...)
	msg.RequestIDLen = uint16(len(msg.RequestID))
	buf = appendUint16(buf, msg.RequestIDLen)
	buf = append(buf, []byte(msg.RequestID)...)
	return buf, nil
}

func unmarshalChildUUIDRes(data []byte) (*ChildUUIDRes, error) {
	msg := &ChildUUIDRes{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: ChildUUIDRes.UUIDLen overflow")
	}
	msg.UUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.UUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: ChildUUIDRes.UUID overflow")
	}
	msg.UUID = string(data[:uint64(msg.UUIDLen)])
	data = data[uint64(msg.UUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: ChildUUIDRes.RequestIDLen overflow")
	}
	msg.RequestIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.RequestIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: ChildUUIDRes.RequestID overflow")
	}
	msg.RequestID = string(data[:uint64(msg.RequestIDLen)])
	data = data[uint64(msg.RequestIDLen):]
	_ = data
	return msg, nil
}

func marshalMyInfo(msg *MyInfo) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil MyInfo")
	}
	buf := make([]byte, 0)
	msg.UUIDLen = uint16(len(msg.UUID))
	buf = appendUint16(buf, msg.UUIDLen)
	buf = append(buf, []byte(msg.UUID)...)
	msg.UsernameLen = uint64(len(msg.Username))
	buf = appendUint64(buf, msg.UsernameLen)
	buf = append(buf, []byte(msg.Username)...)
	msg.HostnameLen = uint64(len(msg.Hostname))
	buf = appendUint64(buf, msg.HostnameLen)
	buf = append(buf, []byte(msg.Hostname)...)
	msg.MemoLen = uint64(len(msg.Memo))
	buf = appendUint64(buf, msg.MemoLen)
	buf = append(buf, []byte(msg.Memo)...)
	return buf, nil
}

func unmarshalMyInfo(data []byte) (*MyInfo, error) {
	msg := &MyInfo{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: MyInfo.UUIDLen overflow")
	}
	msg.UUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.UUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: MyInfo.UUID overflow")
	}
	msg.UUID = string(data[:uint64(msg.UUIDLen)])
	data = data[uint64(msg.UUIDLen):]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: MyInfo.UsernameLen overflow")
	}
	msg.UsernameLen = binary.BigEndian.Uint64(data[:8])
	data = data[8:]
	if msg.UsernameLen > uint64(len(data)) {
		return nil, fmt.Errorf("codec: MyInfo.Username overflow")
	}
	msg.Username = string(data[:msg.UsernameLen])
	data = data[msg.UsernameLen:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: MyInfo.HostnameLen overflow")
	}
	msg.HostnameLen = binary.BigEndian.Uint64(data[:8])
	data = data[8:]
	if msg.HostnameLen > uint64(len(data)) {
		return nil, fmt.Errorf("codec: MyInfo.Hostname overflow")
	}
	msg.Hostname = string(data[:msg.HostnameLen])
	data = data[msg.HostnameLen:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: MyInfo.MemoLen overflow")
	}
	msg.MemoLen = binary.BigEndian.Uint64(data[:8])
	data = data[8:]
	if msg.MemoLen > uint64(len(data)) {
		return nil, fmt.Errorf("codec: MyInfo.Memo overflow")
	}
	msg.Memo = string(data[:msg.MemoLen])
	data = data[msg.MemoLen:]
	_ = data
	return msg, nil
}

func marshalMyMemo(msg *MyMemo) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil MyMemo")
	}
	buf := make([]byte, 0)
	msg.MemoLen = uint64(len(msg.Memo))
	buf = appendUint64(buf, msg.MemoLen)
	buf = append(buf, []byte(msg.Memo)...)
	return buf, nil
}

func unmarshalMyMemo(data []byte) (*MyMemo, error) {
	msg := &MyMemo{}
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: MyMemo.MemoLen overflow")
	}
	msg.MemoLen = binary.BigEndian.Uint64(data[:8])
	data = data[8:]
	if msg.MemoLen > uint64(len(data)) {
		return nil, fmt.Errorf("codec: MyMemo.Memo overflow")
	}
	msg.Memo = string(data[:msg.MemoLen])
	data = data[msg.MemoLen:]
	_ = data
	return msg, nil
}

func marshalListenReq(msg *ListenReq) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil ListenReq")
	}
	buf := make([]byte, 0)
	buf = appendUint16(buf, msg.Method)
	msg.AddrLen = uint64(len(msg.Addr))
	buf = appendUint64(buf, msg.AddrLen)
	buf = append(buf, []byte(msg.Addr)...)
	msg.ListenerIDLen = uint16(len(msg.ListenerID))
	buf = appendUint16(buf, msg.ListenerIDLen)
	buf = append(buf, []byte(msg.ListenerID)...)
	return buf, nil
}

func unmarshalListenReq(data []byte) (*ListenReq, error) {
	msg := &ListenReq{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: ListenReq.Method overflow")
	}
	msg.Method = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: ListenReq.AddrLen overflow")
	}
	msg.AddrLen = binary.BigEndian.Uint64(data[:8])
	data = data[8:]
	if msg.AddrLen > uint64(len(data)) {
		return nil, fmt.Errorf("codec: ListenReq.Addr overflow")
	}
	msg.Addr = string(data[:msg.AddrLen])
	data = data[msg.AddrLen:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: ListenReq.ListenerIDLen overflow")
	}
	msg.ListenerIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ListenerIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: ListenReq.ListenerID overflow")
	}
	msg.ListenerID = string(data[:uint64(msg.ListenerIDLen)])
	data = data[uint64(msg.ListenerIDLen):]
	_ = data
	return msg, nil
}

func marshalListenRes(msg *ListenRes) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil ListenRes")
	}
	buf := make([]byte, 0)
	buf = appendUint16(buf, msg.OK)
	msg.ListenerIDLen = uint16(len(msg.ListenerID))
	buf = appendUint16(buf, msg.ListenerIDLen)
	buf = append(buf, []byte(msg.ListenerID)...)
	return buf, nil
}

func unmarshalListenRes(data []byte) (*ListenRes, error) {
	msg := &ListenRes{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: ListenRes.OK overflow")
	}
	msg.OK = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: ListenRes.ListenerIDLen overflow")
	}
	msg.ListenerIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ListenerIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: ListenRes.ListenerID overflow")
	}
	msg.ListenerID = string(data[:uint64(msg.ListenerIDLen)])
	data = data[uint64(msg.ListenerIDLen):]
	_ = data
	return msg, nil
}

func marshalListenStop(msg *ListenStop) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil ListenStop")
	}
	buf := make([]byte, 0)
	msg.ListenerIDLen = uint16(len(msg.ListenerID))
	buf = appendUint16(buf, msg.ListenerIDLen)
	buf = append(buf, []byte(msg.ListenerID)...)
	return buf, nil
}

func unmarshalListenStop(data []byte) (*ListenStop, error) {
	msg := &ListenStop{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: ListenStop.ListenerIDLen overflow")
	}
	msg.ListenerIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ListenerIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: ListenStop.ListenerID overflow")
	}
	msg.ListenerID = string(data[:uint64(msg.ListenerIDLen)])
	data = data[uint64(msg.ListenerIDLen):]
	_ = data
	return msg, nil
}

func marshalConnectStart(msg *ConnectStart) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil ConnectStart")
	}
	buf := make([]byte, 0)
	msg.AddrLen = uint16(len(msg.Addr))
	buf = appendUint16(buf, msg.AddrLen)
	buf = append(buf, []byte(msg.Addr)...)
	return buf, nil
}

func unmarshalConnectStart(data []byte) (*ConnectStart, error) {
	msg := &ConnectStart{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: ConnectStart.AddrLen overflow")
	}
	msg.AddrLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.AddrLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: ConnectStart.Addr overflow")
	}
	msg.Addr = string(data[:uint64(msg.AddrLen)])
	data = data[uint64(msg.AddrLen):]
	_ = data
	return msg, nil
}

func marshalConnectDone(msg *ConnectDone) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil ConnectDone")
	}
	buf := make([]byte, 0)
	buf = appendUint16(buf, msg.OK)
	return buf, nil
}

func unmarshalConnectDone(data []byte) (*ConnectDone, error) {
	msg := &ConnectDone{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: ConnectDone.OK overflow")
	}
	msg.OK = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalNodeConnInfo(msg *NodeConnInfo) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil NodeConnInfo")
	}
	buf := make([]byte, 0)
	msg.UUIDLen = uint16(len(msg.UUID))
	buf = appendUint16(buf, msg.UUIDLen)
	buf = append(buf, []byte(msg.UUID)...)
	msg.DialAddrLen = uint16(len(msg.DialAddress))
	buf = appendUint16(buf, msg.DialAddrLen)
	buf = append(buf, []byte(msg.DialAddress)...)
	buf = appendUint16(buf, msg.ListenPort)
	buf = appendUint16(buf, msg.FallbackPort)
	msg.TransportLen = uint16(len(msg.Transport))
	buf = appendUint16(buf, msg.TransportLen)
	buf = append(buf, []byte(msg.Transport)...)
	buf = appendUint16(buf, msg.TlsEnabled)
	buf = appendInt64(buf, msg.LastSuccessUnix)
	return buf, nil
}

func unmarshalNodeConnInfo(data []byte) (*NodeConnInfo, error) {
	msg := &NodeConnInfo{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: NodeConnInfo.UUIDLen overflow")
	}
	msg.UUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.UUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: NodeConnInfo.UUID overflow")
	}
	msg.UUID = string(data[:uint64(msg.UUIDLen)])
	data = data[uint64(msg.UUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: NodeConnInfo.DialAddrLen overflow")
	}
	msg.DialAddrLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.DialAddrLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: NodeConnInfo.DialAddress overflow")
	}
	msg.DialAddress = string(data[:uint64(msg.DialAddrLen)])
	data = data[uint64(msg.DialAddrLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: NodeConnInfo.ListenPort overflow")
	}
	msg.ListenPort = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: NodeConnInfo.FallbackPort overflow")
	}
	msg.FallbackPort = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: NodeConnInfo.TransportLen overflow")
	}
	msg.TransportLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.TransportLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: NodeConnInfo.Transport overflow")
	}
	msg.Transport = string(data[:uint64(msg.TransportLen)])
	data = data[uint64(msg.TransportLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: NodeConnInfo.TlsEnabled overflow")
	}
	msg.TlsEnabled = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: NodeConnInfo.LastSuccessUnix overflow")
	}
	msg.LastSuccessUnix = int64(binary.BigEndian.Uint64(data[:8]))
	data = data[8:]
	_ = data
	return msg, nil
}

func marshalNodeOffline(msg *NodeOffline) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil NodeOffline")
	}
	buf := make([]byte, 0)
	msg.UUIDLen = uint16(len(msg.UUID))
	buf = appendUint16(buf, msg.UUIDLen)
	buf = append(buf, []byte(msg.UUID)...)
	return buf, nil
}

func unmarshalNodeOffline(data []byte) (*NodeOffline, error) {
	msg := &NodeOffline{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: NodeOffline.UUIDLen overflow")
	}
	msg.UUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.UUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: NodeOffline.UUID overflow")
	}
	msg.UUID = string(data[:uint64(msg.UUIDLen)])
	data = data[uint64(msg.UUIDLen):]
	_ = data
	return msg, nil
}

func marshalNodeReonline(msg *NodeReonline) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil NodeReonline")
	}
	buf := make([]byte, 0)
	msg.ParentUUIDLen = uint16(len(msg.ParentUUID))
	buf = appendUint16(buf, msg.ParentUUIDLen)
	buf = append(buf, []byte(msg.ParentUUID)...)
	msg.UUIDLen = uint16(len(msg.UUID))
	buf = appendUint16(buf, msg.UUIDLen)
	buf = append(buf, []byte(msg.UUID)...)
	msg.IPLen = uint16(len(msg.IP))
	buf = appendUint16(buf, msg.IPLen)
	buf = append(buf, []byte(msg.IP)...)
	return buf, nil
}

func unmarshalNodeReonline(data []byte) (*NodeReonline, error) {
	msg := &NodeReonline{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: NodeReonline.ParentUUIDLen overflow")
	}
	msg.ParentUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ParentUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: NodeReonline.ParentUUID overflow")
	}
	msg.ParentUUID = string(data[:uint64(msg.ParentUUIDLen)])
	data = data[uint64(msg.ParentUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: NodeReonline.UUIDLen overflow")
	}
	msg.UUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.UUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: NodeReonline.UUID overflow")
	}
	msg.UUID = string(data[:uint64(msg.UUIDLen)])
	data = data[uint64(msg.UUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: NodeReonline.IPLen overflow")
	}
	msg.IPLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.IPLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: NodeReonline.IP overflow")
	}
	msg.IP = string(data[:uint64(msg.IPLen)])
	data = data[uint64(msg.IPLen):]
	_ = data
	return msg, nil
}

func marshalUpstreamOffline(msg *UpstreamOffline) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil UpstreamOffline")
	}
	buf := make([]byte, 0)
	buf = appendUint16(buf, msg.OK)
	return buf, nil
}

func unmarshalUpstreamOffline(data []byte) (*UpstreamOffline, error) {
	msg := &UpstreamOffline{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: UpstreamOffline.OK overflow")
	}
	msg.OK = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalUpstreamReonline(msg *UpstreamReonline) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil UpstreamReonline")
	}
	buf := make([]byte, 0)
	buf = appendUint16(buf, msg.OK)
	return buf, nil
}

func unmarshalUpstreamReonline(data []byte) (*UpstreamReonline, error) {
	msg := &UpstreamReonline{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: UpstreamReonline.OK overflow")
	}
	msg.OK = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalShutdown(msg *Shutdown) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil Shutdown")
	}
	buf := make([]byte, 0)
	buf = appendUint16(buf, msg.OK)
	return buf, nil
}

func unmarshalShutdown(data []byte) (*Shutdown, error) {
	msg := &Shutdown{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: Shutdown.OK overflow")
	}
	msg.OK = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalHeartbeatMsg(msg *HeartbeatMsg) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil HeartbeatMsg")
	}
	buf := make([]byte, 0)
	buf = appendUint16(buf, msg.Ping)
	return buf, nil
}

func unmarshalHeartbeatMsg(data []byte) (*HeartbeatMsg, error) {
	msg := &HeartbeatMsg{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: HeartbeatMsg.Ping overflow")
	}
	msg.Ping = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalRuntimeLog(msg *RuntimeLog) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil RuntimeLog")
	}
	buf := make([]byte, 0)
	msg.UUIDLen = uint16(len(msg.UUID))
	buf = appendUint16(buf, msg.UUIDLen)
	buf = append(buf, []byte(msg.UUID)...)
	msg.SeverityLen = uint16(len(msg.Severity))
	buf = appendUint16(buf, msg.SeverityLen)
	buf = append(buf, []byte(msg.Severity)...)
	msg.CodeLen = uint16(len(msg.Code))
	buf = appendUint16(buf, msg.CodeLen)
	buf = append(buf, []byte(msg.Code)...)
	msg.MessageLen = uint64(len(msg.Message))
	buf = appendUint64(buf, msg.MessageLen)
	buf = append(buf, []byte(msg.Message)...)
	buf = appendUint16(buf, msg.Retryable)
	msg.CauseLen = uint64(len(msg.Cause))
	buf = appendUint64(buf, msg.CauseLen)
	buf = append(buf, []byte(msg.Cause)...)
	return buf, nil
}

func unmarshalRuntimeLog(data []byte) (*RuntimeLog, error) {
	msg := &RuntimeLog{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RuntimeLog.UUIDLen overflow")
	}
	msg.UUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.UUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RuntimeLog.UUID overflow")
	}
	msg.UUID = string(data[:uint64(msg.UUIDLen)])
	data = data[uint64(msg.UUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RuntimeLog.SeverityLen overflow")
	}
	msg.SeverityLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.SeverityLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RuntimeLog.Severity overflow")
	}
	msg.Severity = string(data[:uint64(msg.SeverityLen)])
	data = data[uint64(msg.SeverityLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RuntimeLog.CodeLen overflow")
	}
	msg.CodeLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.CodeLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RuntimeLog.Code overflow")
	}
	msg.Code = string(data[:uint64(msg.CodeLen)])
	data = data[uint64(msg.CodeLen):]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: RuntimeLog.MessageLen overflow")
	}
	msg.MessageLen = binary.BigEndian.Uint64(data[:8])
	data = data[8:]
	if msg.MessageLen > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RuntimeLog.Message overflow")
	}
	msg.Message = string(data[:msg.MessageLen])
	data = data[msg.MessageLen:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RuntimeLog.Retryable overflow")
	}
	msg.Retryable = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: RuntimeLog.CauseLen overflow")
	}
	msg.CauseLen = binary.BigEndian.Uint64(data[:8])
	data = data[8:]
	if msg.CauseLen > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RuntimeLog.Cause overflow")
	}
	msg.Cause = string(data[:msg.CauseLen])
	data = data[msg.CauseLen:]
	_ = data
	return msg, nil
}

func marshalGossipUpdate(msg *GossipUpdate) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil GossipUpdate")
	}
	buf := make([]byte, 0)
	buf = appendInt32(buf, msg.TTL)
	msg.NodeDataLen = uint64(len(msg.NodeData))
	buf = appendUint64(buf, msg.NodeDataLen)
	buf = append(buf, msg.NodeData...)
	msg.SenderUUIDLen = uint16(len(msg.SenderUUID))
	buf = appendUint16(buf, msg.SenderUUIDLen)
	buf = append(buf, []byte(msg.SenderUUID)...)
	buf = appendInt64(buf, msg.Timestamp)
	return buf, nil
}

func unmarshalGossipUpdate(data []byte) (*GossipUpdate, error) {
	msg := &GossipUpdate{}
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: GossipUpdate.TTL overflow")
	}
	msg.TTL = int32(binary.BigEndian.Uint32(data[:4]))
	data = data[4:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: GossipUpdate.NodeDataLen overflow")
	}
	msg.NodeDataLen = binary.BigEndian.Uint64(data[:8])
	data = data[8:]
	if msg.NodeDataLen > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipUpdate.NodeData overflow")
	}
	msg.NodeData = append([]byte(nil), data[:msg.NodeDataLen]...)
	data = data[msg.NodeDataLen:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipUpdate.SenderUUIDLen overflow")
	}
	msg.SenderUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.SenderUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipUpdate.SenderUUID overflow")
	}
	msg.SenderUUID = string(data[:uint64(msg.SenderUUIDLen)])
	data = data[uint64(msg.SenderUUIDLen):]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: GossipUpdate.Timestamp overflow")
	}
	msg.Timestamp = int64(binary.BigEndian.Uint64(data[:8]))
	data = data[8:]
	_ = data
	return msg, nil
}

func marshalGossipRequest(msg *GossipRequest) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil GossipRequest")
	}
	buf := make([]byte, 0)
	msg.RequestUUIDLen = uint16(len(msg.RequestUUID))
	buf = appendUint16(buf, msg.RequestUUIDLen)
	buf = append(buf, []byte(msg.RequestUUID)...)
	msg.RequesterUUIDLen = uint16(len(msg.RequesterUUID))
	buf = appendUint16(buf, msg.RequesterUUIDLen)
	buf = append(buf, []byte(msg.RequesterUUID)...)
	msg.TargetUUIDLen = uint16(len(msg.TargetUUID))
	buf = appendUint16(buf, msg.TargetUUIDLen)
	buf = append(buf, []byte(msg.TargetUUID)...)
	buf = appendInt64(buf, msg.Timestamp)
	return buf, nil
}

func unmarshalGossipRequest(data []byte) (*GossipRequest, error) {
	msg := &GossipRequest{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipRequest.RequestUUIDLen overflow")
	}
	msg.RequestUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.RequestUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipRequest.RequestUUID overflow")
	}
	msg.RequestUUID = string(data[:uint64(msg.RequestUUIDLen)])
	data = data[uint64(msg.RequestUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipRequest.RequesterUUIDLen overflow")
	}
	msg.RequesterUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.RequesterUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipRequest.RequesterUUID overflow")
	}
	msg.RequesterUUID = string(data[:uint64(msg.RequesterUUIDLen)])
	data = data[uint64(msg.RequesterUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipRequest.TargetUUIDLen overflow")
	}
	msg.TargetUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.TargetUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipRequest.TargetUUID overflow")
	}
	msg.TargetUUID = string(data[:uint64(msg.TargetUUIDLen)])
	data = data[uint64(msg.TargetUUIDLen):]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: GossipRequest.Timestamp overflow")
	}
	msg.Timestamp = int64(binary.BigEndian.Uint64(data[:8]))
	data = data[8:]
	_ = data
	return msg, nil
}

func marshalGossipResponse(msg *GossipResponse) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil GossipResponse")
	}
	buf := make([]byte, 0)
	msg.RequestUUIDLen = uint16(len(msg.RequestUUID))
	buf = appendUint16(buf, msg.RequestUUIDLen)
	buf = append(buf, []byte(msg.RequestUUID)...)
	msg.RequesterUUIDLen = uint16(len(msg.RequesterUUID))
	buf = appendUint16(buf, msg.RequesterUUIDLen)
	buf = append(buf, []byte(msg.RequesterUUID)...)
	msg.ResponderUUIDLen = uint16(len(msg.ResponderUUID))
	buf = appendUint16(buf, msg.ResponderUUIDLen)
	buf = append(buf, []byte(msg.ResponderUUID)...)
	msg.TargetUUIDLen = uint16(len(msg.TargetUUID))
	buf = appendUint16(buf, msg.TargetUUIDLen)
	buf = append(buf, []byte(msg.TargetUUID)...)
	buf = appendBool(buf, msg.Reachable)
	buf = appendInt64(buf, msg.Latency)
	msg.NodeDataLen = uint64(len(msg.NodeData))
	buf = appendUint64(buf, msg.NodeDataLen)
	buf = append(buf, msg.NodeData...)
	buf = appendInt64(buf, msg.Timestamp)
	return buf, nil
}

func unmarshalGossipResponse(data []byte) (*GossipResponse, error) {
	msg := &GossipResponse{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipResponse.RequestUUIDLen overflow")
	}
	msg.RequestUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.RequestUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipResponse.RequestUUID overflow")
	}
	msg.RequestUUID = string(data[:uint64(msg.RequestUUIDLen)])
	data = data[uint64(msg.RequestUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipResponse.RequesterUUIDLen overflow")
	}
	msg.RequesterUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.RequesterUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipResponse.RequesterUUID overflow")
	}
	msg.RequesterUUID = string(data[:uint64(msg.RequesterUUIDLen)])
	data = data[uint64(msg.RequesterUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipResponse.ResponderUUIDLen overflow")
	}
	msg.ResponderUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ResponderUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipResponse.ResponderUUID overflow")
	}
	msg.ResponderUUID = string(data[:uint64(msg.ResponderUUIDLen)])
	data = data[uint64(msg.ResponderUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipResponse.TargetUUIDLen overflow")
	}
	msg.TargetUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.TargetUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipResponse.TargetUUID overflow")
	}
	msg.TargetUUID = string(data[:uint64(msg.TargetUUIDLen)])
	data = data[uint64(msg.TargetUUIDLen):]
	if len(data) < 1 {
		return nil, fmt.Errorf("codec: GossipResponse.Reachable overflow")
	}
	msg.Reachable = data[0] != 0
	data = data[1:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: GossipResponse.Latency overflow")
	}
	msg.Latency = int64(binary.BigEndian.Uint64(data[:8]))
	data = data[8:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: GossipResponse.NodeDataLen overflow")
	}
	msg.NodeDataLen = binary.BigEndian.Uint64(data[:8])
	data = data[8:]
	if msg.NodeDataLen > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipResponse.NodeData overflow")
	}
	msg.NodeData = append([]byte(nil), data[:msg.NodeDataLen]...)
	data = data[msg.NodeDataLen:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: GossipResponse.Timestamp overflow")
	}
	msg.Timestamp = int64(binary.BigEndian.Uint64(data[:8]))
	data = data[8:]
	_ = data
	return msg, nil
}

func marshalGossipDiscover(msg *GossipDiscover) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil GossipDiscover")
	}
	buf := make([]byte, 0)
	msg.SenderUUIDLen = uint16(len(msg.SenderUUID))
	buf = appendUint16(buf, msg.SenderUUIDLen)
	buf = append(buf, []byte(msg.SenderUUID)...)
	msg.SenderIPLen = uint16(len(msg.SenderIP))
	buf = appendUint16(buf, msg.SenderIPLen)
	buf = append(buf, []byte(msg.SenderIP)...)
	buf = appendUint16(buf, msg.SenderPort)
	buf = appendInt64(buf, msg.Timestamp)
	return buf, nil
}

func unmarshalGossipDiscover(data []byte) (*GossipDiscover, error) {
	msg := &GossipDiscover{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipDiscover.SenderUUIDLen overflow")
	}
	msg.SenderUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.SenderUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipDiscover.SenderUUID overflow")
	}
	msg.SenderUUID = string(data[:uint64(msg.SenderUUIDLen)])
	data = data[uint64(msg.SenderUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipDiscover.SenderIPLen overflow")
	}
	msg.SenderIPLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.SenderIPLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipDiscover.SenderIP overflow")
	}
	msg.SenderIP = string(data[:uint64(msg.SenderIPLen)])
	data = data[uint64(msg.SenderIPLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipDiscover.SenderPort overflow")
	}
	msg.SenderPort = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: GossipDiscover.Timestamp overflow")
	}
	msg.Timestamp = int64(binary.BigEndian.Uint64(data[:8]))
	data = data[8:]
	_ = data
	return msg, nil
}

func marshalGossipHeartbeat(msg *GossipHeartbeat) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil GossipHeartbeat")
	}
	buf := make([]byte, 0)
	msg.SenderUUIDLen = uint16(len(msg.SenderUUID))
	buf = appendUint16(buf, msg.SenderUUIDLen)
	buf = append(buf, []byte(msg.SenderUUID)...)
	buf = appendInt32(buf, msg.Status)
	buf = appendInt32(buf, msg.Load)
	buf = appendInt64(buf, msg.Timestamp)
	return buf, nil
}

func unmarshalGossipHeartbeat(data []byte) (*GossipHeartbeat, error) {
	msg := &GossipHeartbeat{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipHeartbeat.SenderUUIDLen overflow")
	}
	msg.SenderUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.SenderUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipHeartbeat.SenderUUID overflow")
	}
	msg.SenderUUID = string(data[:uint64(msg.SenderUUIDLen)])
	data = data[uint64(msg.SenderUUIDLen):]
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: GossipHeartbeat.Status overflow")
	}
	msg.Status = int32(binary.BigEndian.Uint32(data[:4]))
	data = data[4:]
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: GossipHeartbeat.Load overflow")
	}
	msg.Load = int32(binary.BigEndian.Uint32(data[:4]))
	data = data[4:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: GossipHeartbeat.Timestamp overflow")
	}
	msg.Timestamp = int64(binary.BigEndian.Uint64(data[:8]))
	data = data[8:]
	_ = data
	return msg, nil
}

func marshalGossipRouteUpdate(msg *GossipRouteUpdate) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil GossipRouteUpdate")
	}
	buf := make([]byte, 0)
	msg.SenderUUIDLen = uint16(len(msg.SenderUUID))
	buf = appendUint16(buf, msg.SenderUUIDLen)
	buf = append(buf, []byte(msg.SenderUUID)...)
	msg.TargetUUIDLen = uint16(len(msg.TargetUUID))
	buf = appendUint16(buf, msg.TargetUUIDLen)
	buf = append(buf, []byte(msg.TargetUUID)...)
	msg.NextHopUUIDLen = uint16(len(msg.NextHopUUID))
	buf = appendUint16(buf, msg.NextHopUUIDLen)
	buf = append(buf, []byte(msg.NextHopUUID)...)
	buf = appendInt32(buf, msg.HopCount)
	buf = appendInt32(buf, msg.Weight)
	buf = appendBool(buf, msg.IsReachable)
	buf = appendInt64(buf, msg.Timestamp)
	return buf, nil
}

func unmarshalGossipRouteUpdate(data []byte) (*GossipRouteUpdate, error) {
	msg := &GossipRouteUpdate{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipRouteUpdate.SenderUUIDLen overflow")
	}
	msg.SenderUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.SenderUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipRouteUpdate.SenderUUID overflow")
	}
	msg.SenderUUID = string(data[:uint64(msg.SenderUUIDLen)])
	data = data[uint64(msg.SenderUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipRouteUpdate.TargetUUIDLen overflow")
	}
	msg.TargetUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.TargetUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipRouteUpdate.TargetUUID overflow")
	}
	msg.TargetUUID = string(data[:uint64(msg.TargetUUIDLen)])
	data = data[uint64(msg.TargetUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipRouteUpdate.NextHopUUIDLen overflow")
	}
	msg.NextHopUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.NextHopUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipRouteUpdate.NextHopUUID overflow")
	}
	msg.NextHopUUID = string(data[:uint64(msg.NextHopUUIDLen)])
	data = data[uint64(msg.NextHopUUIDLen):]
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: GossipRouteUpdate.HopCount overflow")
	}
	msg.HopCount = int32(binary.BigEndian.Uint32(data[:4]))
	data = data[4:]
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: GossipRouteUpdate.Weight overflow")
	}
	msg.Weight = int32(binary.BigEndian.Uint32(data[:4]))
	data = data[4:]
	if len(data) < 1 {
		return nil, fmt.Errorf("codec: GossipRouteUpdate.IsReachable overflow")
	}
	msg.IsReachable = data[0] != 0
	data = data[1:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: GossipRouteUpdate.Timestamp overflow")
	}
	msg.Timestamp = int64(binary.BigEndian.Uint64(data[:8]))
	data = data[8:]
	_ = data
	return msg, nil
}

func marshalGossipNodeJoin(msg *GossipNodeJoin) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil GossipNodeJoin")
	}
	buf := make([]byte, 0)
	msg.NodeUUIDLen = uint16(len(msg.NodeUUID))
	buf = appendUint16(buf, msg.NodeUUIDLen)
	buf = append(buf, []byte(msg.NodeUUID)...)
	msg.NodeIPLen = uint16(len(msg.NodeIP))
	buf = appendUint16(buf, msg.NodeIPLen)
	buf = append(buf, []byte(msg.NodeIP)...)
	buf = appendUint16(buf, msg.NodePort)
	msg.ParentUUIDLen = uint16(len(msg.ParentUUID))
	buf = appendUint16(buf, msg.ParentUUIDLen)
	buf = append(buf, []byte(msg.ParentUUID)...)
	buf = appendInt64(buf, msg.Timestamp)
	return buf, nil
}

func unmarshalGossipNodeJoin(data []byte) (*GossipNodeJoin, error) {
	msg := &GossipNodeJoin{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipNodeJoin.NodeUUIDLen overflow")
	}
	msg.NodeUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.NodeUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipNodeJoin.NodeUUID overflow")
	}
	msg.NodeUUID = string(data[:uint64(msg.NodeUUIDLen)])
	data = data[uint64(msg.NodeUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipNodeJoin.NodeIPLen overflow")
	}
	msg.NodeIPLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.NodeIPLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipNodeJoin.NodeIP overflow")
	}
	msg.NodeIP = string(data[:uint64(msg.NodeIPLen)])
	data = data[uint64(msg.NodeIPLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipNodeJoin.NodePort overflow")
	}
	msg.NodePort = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipNodeJoin.ParentUUIDLen overflow")
	}
	msg.ParentUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ParentUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipNodeJoin.ParentUUID overflow")
	}
	msg.ParentUUID = string(data[:uint64(msg.ParentUUIDLen)])
	data = data[uint64(msg.ParentUUIDLen):]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: GossipNodeJoin.Timestamp overflow")
	}
	msg.Timestamp = int64(binary.BigEndian.Uint64(data[:8]))
	data = data[8:]
	_ = data
	return msg, nil
}

func marshalGossipNodeLeave(msg *GossipNodeLeave) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil GossipNodeLeave")
	}
	buf := make([]byte, 0)
	msg.NodeUUIDLen = uint16(len(msg.NodeUUID))
	buf = appendUint16(buf, msg.NodeUUIDLen)
	buf = append(buf, []byte(msg.NodeUUID)...)
	buf = appendInt32(buf, msg.Reason)
	buf = appendInt64(buf, msg.Timestamp)
	return buf, nil
}

func unmarshalGossipNodeLeave(data []byte) (*GossipNodeLeave, error) {
	msg := &GossipNodeLeave{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: GossipNodeLeave.NodeUUIDLen overflow")
	}
	msg.NodeUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.NodeUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: GossipNodeLeave.NodeUUID overflow")
	}
	msg.NodeUUID = string(data[:uint64(msg.NodeUUIDLen)])
	data = data[uint64(msg.NodeUUIDLen):]
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: GossipNodeLeave.Reason overflow")
	}
	msg.Reason = int32(binary.BigEndian.Uint32(data[:4]))
	data = data[4:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: GossipNodeLeave.Timestamp overflow")
	}
	msg.Timestamp = int64(binary.BigEndian.Uint64(data[:8]))
	data = data[8:]
	_ = data
	return msg, nil
}

func marshalSuppLinkRequest(msg *SuppLinkRequest) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil SuppLinkRequest")
	}
	buf := make([]byte, 0)
	msg.RequestUUIDLen = uint16(len(msg.RequestUUID))
	buf = appendUint16(buf, msg.RequestUUIDLen)
	buf = append(buf, []byte(msg.RequestUUID)...)
	msg.LinkUUIDLen = uint16(len(msg.LinkUUID))
	buf = appendUint16(buf, msg.LinkUUIDLen)
	buf = append(buf, []byte(msg.LinkUUID)...)
	msg.InitiatorUUIDLen = uint16(len(msg.InitiatorUUID))
	buf = appendUint16(buf, msg.InitiatorUUIDLen)
	buf = append(buf, []byte(msg.InitiatorUUID)...)
	msg.TargetUUIDLen = uint16(len(msg.TargetUUID))
	buf = appendUint16(buf, msg.TargetUUIDLen)
	buf = append(buf, []byte(msg.TargetUUID)...)
	msg.PeerIPLen = uint16(len(msg.PeerIP))
	buf = appendUint16(buf, msg.PeerIPLen)
	buf = append(buf, []byte(msg.PeerIP)...)
	buf = appendUint16(buf, msg.PeerPort)
	buf = appendUint16(buf, msg.Action)
	buf = appendUint16(buf, msg.Role)
	buf = appendUint16(buf, msg.Flags)
	buf = appendUint32(buf, msg.Timeout)
	return buf, nil
}

func unmarshalSuppLinkRequest(data []byte) (*SuppLinkRequest, error) {
	msg := &SuppLinkRequest{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkRequest.RequestUUIDLen overflow")
	}
	msg.RequestUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.RequestUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkRequest.RequestUUID overflow")
	}
	msg.RequestUUID = string(data[:uint64(msg.RequestUUIDLen)])
	data = data[uint64(msg.RequestUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkRequest.LinkUUIDLen overflow")
	}
	msg.LinkUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.LinkUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkRequest.LinkUUID overflow")
	}
	msg.LinkUUID = string(data[:uint64(msg.LinkUUIDLen)])
	data = data[uint64(msg.LinkUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkRequest.InitiatorUUIDLen overflow")
	}
	msg.InitiatorUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.InitiatorUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkRequest.InitiatorUUID overflow")
	}
	msg.InitiatorUUID = string(data[:uint64(msg.InitiatorUUIDLen)])
	data = data[uint64(msg.InitiatorUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkRequest.TargetUUIDLen overflow")
	}
	msg.TargetUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.TargetUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkRequest.TargetUUID overflow")
	}
	msg.TargetUUID = string(data[:uint64(msg.TargetUUIDLen)])
	data = data[uint64(msg.TargetUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkRequest.PeerIPLen overflow")
	}
	msg.PeerIPLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.PeerIPLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkRequest.PeerIP overflow")
	}
	msg.PeerIP = string(data[:uint64(msg.PeerIPLen)])
	data = data[uint64(msg.PeerIPLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkRequest.PeerPort overflow")
	}
	msg.PeerPort = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkRequest.Action overflow")
	}
	msg.Action = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkRequest.Role overflow")
	}
	msg.Role = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkRequest.Flags overflow")
	}
	msg.Flags = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: SuppLinkRequest.Timeout overflow")
	}
	msg.Timeout = binary.BigEndian.Uint32(data[:4])
	data = data[4:]
	_ = data
	return msg, nil
}

func marshalSuppLinkResponse(msg *SuppLinkResponse) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil SuppLinkResponse")
	}
	buf := make([]byte, 0)
	msg.RequestUUIDLen = uint16(len(msg.RequestUUID))
	buf = appendUint16(buf, msg.RequestUUIDLen)
	buf = append(buf, []byte(msg.RequestUUID)...)
	msg.LinkUUIDLen = uint16(len(msg.LinkUUID))
	buf = appendUint16(buf, msg.LinkUUIDLen)
	buf = append(buf, []byte(msg.LinkUUID)...)
	msg.AgentUUIDLen = uint16(len(msg.AgentUUID))
	buf = appendUint16(buf, msg.AgentUUIDLen)
	buf = append(buf, []byte(msg.AgentUUID)...)
	msg.PeerUUIDLen = uint16(len(msg.PeerUUID))
	buf = appendUint16(buf, msg.PeerUUIDLen)
	buf = append(buf, []byte(msg.PeerUUID)...)
	buf = appendUint16(buf, msg.Role)
	buf = appendUint16(buf, msg.Status)
	msg.MessageLen = uint16(len(msg.Message))
	buf = appendUint16(buf, msg.MessageLen)
	buf = append(buf, []byte(msg.Message)...)
	msg.ListenIPLen = uint16(len(msg.ListenIP))
	buf = appendUint16(buf, msg.ListenIPLen)
	buf = append(buf, []byte(msg.ListenIP)...)
	buf = appendUint16(buf, msg.ListenPort)
	return buf, nil
}

func unmarshalSuppLinkResponse(data []byte) (*SuppLinkResponse, error) {
	msg := &SuppLinkResponse{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkResponse.RequestUUIDLen overflow")
	}
	msg.RequestUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.RequestUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkResponse.RequestUUID overflow")
	}
	msg.RequestUUID = string(data[:uint64(msg.RequestUUIDLen)])
	data = data[uint64(msg.RequestUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkResponse.LinkUUIDLen overflow")
	}
	msg.LinkUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.LinkUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkResponse.LinkUUID overflow")
	}
	msg.LinkUUID = string(data[:uint64(msg.LinkUUIDLen)])
	data = data[uint64(msg.LinkUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkResponse.AgentUUIDLen overflow")
	}
	msg.AgentUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.AgentUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkResponse.AgentUUID overflow")
	}
	msg.AgentUUID = string(data[:uint64(msg.AgentUUIDLen)])
	data = data[uint64(msg.AgentUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkResponse.PeerUUIDLen overflow")
	}
	msg.PeerUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.PeerUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkResponse.PeerUUID overflow")
	}
	msg.PeerUUID = string(data[:uint64(msg.PeerUUIDLen)])
	data = data[uint64(msg.PeerUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkResponse.Role overflow")
	}
	msg.Role = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkResponse.Status overflow")
	}
	msg.Status = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkResponse.MessageLen overflow")
	}
	msg.MessageLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.MessageLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkResponse.Message overflow")
	}
	msg.Message = string(data[:uint64(msg.MessageLen)])
	data = data[uint64(msg.MessageLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkResponse.ListenIPLen overflow")
	}
	msg.ListenIPLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ListenIPLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkResponse.ListenIP overflow")
	}
	msg.ListenIP = string(data[:uint64(msg.ListenIPLen)])
	data = data[uint64(msg.ListenIPLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkResponse.ListenPort overflow")
	}
	msg.ListenPort = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalSuppLinkTeardown(msg *SuppLinkTeardown) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil SuppLinkTeardown")
	}
	buf := make([]byte, 0)
	msg.LinkUUIDLen = uint16(len(msg.LinkUUID))
	buf = appendUint16(buf, msg.LinkUUIDLen)
	buf = append(buf, []byte(msg.LinkUUID)...)
	msg.ReasonLen = uint16(len(msg.Reason))
	buf = appendUint16(buf, msg.ReasonLen)
	buf = append(buf, []byte(msg.Reason)...)
	return buf, nil
}

func unmarshalSuppLinkTeardown(data []byte) (*SuppLinkTeardown, error) {
	msg := &SuppLinkTeardown{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkTeardown.LinkUUIDLen overflow")
	}
	msg.LinkUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.LinkUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkTeardown.LinkUUID overflow")
	}
	msg.LinkUUID = string(data[:uint64(msg.LinkUUIDLen)])
	data = data[uint64(msg.LinkUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkTeardown.ReasonLen overflow")
	}
	msg.ReasonLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ReasonLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkTeardown.Reason overflow")
	}
	msg.Reason = string(data[:uint64(msg.ReasonLen)])
	data = data[uint64(msg.ReasonLen):]
	_ = data
	return msg, nil
}

func marshalSuppLinkHeartbeat(msg *SuppLinkHeartbeat) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil SuppLinkHeartbeat")
	}
	buf := make([]byte, 0)
	msg.LinkUUIDLen = uint16(len(msg.LinkUUID))
	buf = appendUint16(buf, msg.LinkUUIDLen)
	buf = append(buf, []byte(msg.LinkUUID)...)
	msg.PeerUUIDLen = uint16(len(msg.PeerUUID))
	buf = appendUint16(buf, msg.PeerUUIDLen)
	buf = append(buf, []byte(msg.PeerUUID)...)
	buf = appendUint16(buf, msg.Status)
	buf = appendInt64(buf, msg.Timestamp)
	return buf, nil
}

func unmarshalSuppLinkHeartbeat(data []byte) (*SuppLinkHeartbeat, error) {
	msg := &SuppLinkHeartbeat{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkHeartbeat.LinkUUIDLen overflow")
	}
	msg.LinkUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.LinkUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkHeartbeat.LinkUUID overflow")
	}
	msg.LinkUUID = string(data[:uint64(msg.LinkUUIDLen)])
	data = data[uint64(msg.LinkUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkHeartbeat.PeerUUIDLen overflow")
	}
	msg.PeerUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.PeerUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkHeartbeat.PeerUUID overflow")
	}
	msg.PeerUUID = string(data[:uint64(msg.PeerUUIDLen)])
	data = data[uint64(msg.PeerUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkHeartbeat.Status overflow")
	}
	msg.Status = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: SuppLinkHeartbeat.Timestamp overflow")
	}
	msg.Timestamp = int64(binary.BigEndian.Uint64(data[:8]))
	data = data[8:]
	_ = data
	return msg, nil
}

func marshalSuppFailoverCommand(msg *SuppFailoverCommand) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil SuppFailoverCommand")
	}
	buf := make([]byte, 0)
	msg.LinkUUIDLen = uint16(len(msg.LinkUUID))
	buf = appendUint16(buf, msg.LinkUUIDLen)
	buf = append(buf, []byte(msg.LinkUUID)...)
	msg.ParentUUIDLen = uint16(len(msg.ParentUUID))
	buf = appendUint16(buf, msg.ParentUUIDLen)
	buf = append(buf, []byte(msg.ParentUUID)...)
	msg.ChildUUIDLen = uint16(len(msg.ChildUUID))
	buf = appendUint16(buf, msg.ChildUUIDLen)
	buf = append(buf, []byte(msg.ChildUUID)...)
	buf = appendUint16(buf, msg.Role)
	buf = appendUint16(buf, msg.Flags)
	return buf, nil
}

func unmarshalSuppFailoverCommand(data []byte) (*SuppFailoverCommand, error) {
	msg := &SuppFailoverCommand{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppFailoverCommand.LinkUUIDLen overflow")
	}
	msg.LinkUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.LinkUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppFailoverCommand.LinkUUID overflow")
	}
	msg.LinkUUID = string(data[:uint64(msg.LinkUUIDLen)])
	data = data[uint64(msg.LinkUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppFailoverCommand.ParentUUIDLen overflow")
	}
	msg.ParentUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ParentUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppFailoverCommand.ParentUUID overflow")
	}
	msg.ParentUUID = string(data[:uint64(msg.ParentUUIDLen)])
	data = data[uint64(msg.ParentUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppFailoverCommand.ChildUUIDLen overflow")
	}
	msg.ChildUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ChildUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppFailoverCommand.ChildUUID overflow")
	}
	msg.ChildUUID = string(data[:uint64(msg.ChildUUIDLen)])
	data = data[uint64(msg.ChildUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppFailoverCommand.Role overflow")
	}
	msg.Role = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppFailoverCommand.Flags overflow")
	}
	msg.Flags = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalSuppLinkPromote(msg *SuppLinkPromote) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil SuppLinkPromote")
	}
	buf := make([]byte, 0)
	msg.LinkUUIDLen = uint16(len(msg.LinkUUID))
	buf = appendUint16(buf, msg.LinkUUIDLen)
	buf = append(buf, []byte(msg.LinkUUID)...)
	msg.ParentUUIDLen = uint16(len(msg.ParentUUID))
	buf = appendUint16(buf, msg.ParentUUIDLen)
	buf = append(buf, []byte(msg.ParentUUID)...)
	msg.ChildUUIDLen = uint16(len(msg.ChildUUID))
	buf = appendUint16(buf, msg.ChildUUIDLen)
	buf = append(buf, []byte(msg.ChildUUID)...)
	buf = appendUint16(buf, msg.Role)
	return buf, nil
}

func unmarshalSuppLinkPromote(data []byte) (*SuppLinkPromote, error) {
	msg := &SuppLinkPromote{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkPromote.LinkUUIDLen overflow")
	}
	msg.LinkUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.LinkUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkPromote.LinkUUID overflow")
	}
	msg.LinkUUID = string(data[:uint64(msg.LinkUUIDLen)])
	data = data[uint64(msg.LinkUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkPromote.ParentUUIDLen overflow")
	}
	msg.ParentUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ParentUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkPromote.ParentUUID overflow")
	}
	msg.ParentUUID = string(data[:uint64(msg.ParentUUIDLen)])
	data = data[uint64(msg.ParentUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkPromote.ChildUUIDLen overflow")
	}
	msg.ChildUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ChildUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SuppLinkPromote.ChildUUID overflow")
	}
	msg.ChildUUID = string(data[:uint64(msg.ChildUUIDLen)])
	data = data[uint64(msg.ChildUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SuppLinkPromote.Role overflow")
	}
	msg.Role = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalRescueRequest(msg *RescueRequest) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil RescueRequest")
	}
	buf := make([]byte, 0)
	msg.TargetUUIDLen = uint16(len(msg.TargetUUID))
	buf = appendUint16(buf, msg.TargetUUIDLen)
	buf = append(buf, []byte(msg.TargetUUID)...)
	msg.DialAddrLen = uint16(len(msg.DialAddr))
	buf = appendUint16(buf, msg.DialAddrLen)
	buf = append(buf, []byte(msg.DialAddr)...)
	buf = appendUint16(buf, msg.DialPort)
	msg.TransportLen = uint16(len(msg.Transport))
	buf = appendUint16(buf, msg.TransportLen)
	buf = append(buf, []byte(msg.Transport)...)
	msg.SecretLen = uint16(len(msg.Secret))
	buf = appendUint16(buf, msg.SecretLen)
	buf = append(buf, []byte(msg.Secret)...)
	buf = appendUint16(buf, msg.Flags)
	return buf, nil
}

func unmarshalRescueRequest(data []byte) (*RescueRequest, error) {
	msg := &RescueRequest{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RescueRequest.TargetUUIDLen overflow")
	}
	msg.TargetUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.TargetUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RescueRequest.TargetUUID overflow")
	}
	msg.TargetUUID = string(data[:uint64(msg.TargetUUIDLen)])
	data = data[uint64(msg.TargetUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RescueRequest.DialAddrLen overflow")
	}
	msg.DialAddrLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.DialAddrLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RescueRequest.DialAddr overflow")
	}
	msg.DialAddr = string(data[:uint64(msg.DialAddrLen)])
	data = data[uint64(msg.DialAddrLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RescueRequest.DialPort overflow")
	}
	msg.DialPort = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RescueRequest.TransportLen overflow")
	}
	msg.TransportLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.TransportLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RescueRequest.Transport overflow")
	}
	msg.Transport = string(data[:uint64(msg.TransportLen)])
	data = data[uint64(msg.TransportLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RescueRequest.SecretLen overflow")
	}
	msg.SecretLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.SecretLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RescueRequest.Secret overflow")
	}
	msg.Secret = string(data[:uint64(msg.SecretLen)])
	data = data[uint64(msg.SecretLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RescueRequest.Flags overflow")
	}
	msg.Flags = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalRescueResponse(msg *RescueResponse) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil RescueResponse")
	}
	buf := make([]byte, 0)
	msg.TargetUUIDLen = uint16(len(msg.TargetUUID))
	buf = appendUint16(buf, msg.TargetUUIDLen)
	buf = append(buf, []byte(msg.TargetUUID)...)
	msg.RescuerUUIDLen = uint16(len(msg.RescuerUUID))
	buf = appendUint16(buf, msg.RescuerUUIDLen)
	buf = append(buf, []byte(msg.RescuerUUID)...)
	buf = appendUint16(buf, msg.Status)
	msg.MessageLen = uint16(len(msg.Message))
	buf = appendUint16(buf, msg.MessageLen)
	buf = append(buf, []byte(msg.Message)...)
	msg.ParentUUIDLen = uint16(len(msg.ParentUUID))
	buf = appendUint16(buf, msg.ParentUUIDLen)
	buf = append(buf, []byte(msg.ParentUUID)...)
	msg.ChildUUIDLen = uint16(len(msg.ChildUUID))
	buf = appendUint16(buf, msg.ChildUUIDLen)
	buf = append(buf, []byte(msg.ChildUUID)...)
	return buf, nil
}

func unmarshalRescueResponse(data []byte) (*RescueResponse, error) {
	msg := &RescueResponse{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RescueResponse.TargetUUIDLen overflow")
	}
	msg.TargetUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.TargetUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RescueResponse.TargetUUID overflow")
	}
	msg.TargetUUID = string(data[:uint64(msg.TargetUUIDLen)])
	data = data[uint64(msg.TargetUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RescueResponse.RescuerUUIDLen overflow")
	}
	msg.RescuerUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.RescuerUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RescueResponse.RescuerUUID overflow")
	}
	msg.RescuerUUID = string(data[:uint64(msg.RescuerUUIDLen)])
	data = data[uint64(msg.RescuerUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RescueResponse.Status overflow")
	}
	msg.Status = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RescueResponse.MessageLen overflow")
	}
	msg.MessageLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.MessageLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RescueResponse.Message overflow")
	}
	msg.Message = string(data[:uint64(msg.MessageLen)])
	data = data[uint64(msg.MessageLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RescueResponse.ParentUUIDLen overflow")
	}
	msg.ParentUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ParentUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RescueResponse.ParentUUID overflow")
	}
	msg.ParentUUID = string(data[:uint64(msg.ParentUUIDLen)])
	data = data[uint64(msg.ParentUUIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: RescueResponse.ChildUUIDLen overflow")
	}
	msg.ChildUUIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ChildUUIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: RescueResponse.ChildUUID overflow")
	}
	msg.ChildUUID = string(data[:uint64(msg.ChildUUIDLen)])
	data = data[uint64(msg.ChildUUIDLen):]
	_ = data
	return msg, nil
}

func marshalDTNData(msg *DTNData) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil DTNData")
	}
	buf := make([]byte, 0)
	msg.BundleIDLen = uint16(len(msg.BundleID))
	buf = appendUint16(buf, msg.BundleIDLen)
	buf = append(buf, []byte(msg.BundleID)...)
	msg.PayloadLen = uint64(len(msg.Payload))
	buf = appendUint64(buf, msg.PayloadLen)
	buf = append(buf, msg.Payload...)
	return buf, nil
}

func unmarshalDTNData(data []byte) (*DTNData, error) {
	msg := &DTNData{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: DTNData.BundleIDLen overflow")
	}
	msg.BundleIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.BundleIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: DTNData.BundleID overflow")
	}
	msg.BundleID = string(data[:uint64(msg.BundleIDLen)])
	data = data[uint64(msg.BundleIDLen):]
	if len(data) < 8 {
		return nil, fmt.Errorf("codec: DTNData.PayloadLen overflow")
	}
	msg.PayloadLen = binary.BigEndian.Uint64(data[:8])
	data = data[8:]
	if msg.PayloadLen > uint64(len(data)) {
		return nil, fmt.Errorf("codec: DTNData.Payload overflow")
	}
	msg.Payload = append([]byte(nil), data[:msg.PayloadLen]...)
	data = data[msg.PayloadLen:]
	_ = data
	return msg, nil
}

func marshalDTNAck(msg *DTNAck) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil DTNAck")
	}
	buf := make([]byte, 0)
	msg.BundleIDLen = uint16(len(msg.BundleID))
	buf = appendUint16(buf, msg.BundleIDLen)
	buf = append(buf, []byte(msg.BundleID)...)
	buf = appendUint16(buf, msg.OK)
	msg.ErrorLen = uint16(len(msg.Error))
	buf = appendUint16(buf, msg.ErrorLen)
	buf = append(buf, []byte(msg.Error)...)
	return buf, nil
}

func unmarshalDTNAck(data []byte) (*DTNAck, error) {
	msg := &DTNAck{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: DTNAck.BundleIDLen overflow")
	}
	msg.BundleIDLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.BundleIDLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: DTNAck.BundleID overflow")
	}
	msg.BundleID = string(data[:uint64(msg.BundleIDLen)])
	data = data[uint64(msg.BundleIDLen):]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: DTNAck.OK overflow")
	}
	msg.OK = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: DTNAck.ErrorLen overflow")
	}
	msg.ErrorLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ErrorLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: DTNAck.Error overflow")
	}
	msg.Error = string(data[:uint64(msg.ErrorLen)])
	data = data[uint64(msg.ErrorLen):]
	_ = data
	return msg, nil
}

func marshalDTNPull(msg *DTNPull) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil DTNPull")
	}
	buf := make([]byte, 0)
	buf = appendUint16(buf, msg.Limit)
	return buf, nil
}

func unmarshalDTNPull(data []byte) (*DTNPull, error) {
	msg := &DTNPull{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: DTNPull.Limit overflow")
	}
	msg.Limit = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalStreamOpen(msg *StreamOpen) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil StreamOpen")
	}
	buf := make([]byte, 0)
	buf = appendUint32(buf, msg.StreamID)
	msg.OptionsLen = uint16(len(msg.Options))
	buf = appendUint16(buf, msg.OptionsLen)
	buf = append(buf, []byte(msg.Options)...)
	return buf, nil
}

func unmarshalStreamOpen(data []byte) (*StreamOpen, error) {
	msg := &StreamOpen{}
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: StreamOpen.StreamID overflow")
	}
	msg.StreamID = binary.BigEndian.Uint32(data[:4])
	data = data[4:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: StreamOpen.OptionsLen overflow")
	}
	msg.OptionsLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.OptionsLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: StreamOpen.Options overflow")
	}
	msg.Options = string(data[:uint64(msg.OptionsLen)])
	data = data[uint64(msg.OptionsLen):]
	_ = data
	return msg, nil
}

func marshalStreamData(msg *StreamData) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil StreamData")
	}
	buf := make([]byte, 0)
	buf = appendUint32(buf, msg.StreamID)
	buf = appendUint32(buf, msg.Seq)
	buf = appendUint32(buf, msg.Ack)
	buf = appendUint16(buf, msg.Window)
	msg.PayloadLen = uint32(len(msg.Payload))
	buf = appendUint32(buf, msg.PayloadLen)
	buf = append(buf, msg.Payload...)
	return buf, nil
}

func unmarshalStreamData(data []byte) (*StreamData, error) {
	msg := &StreamData{}
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: StreamData.StreamID overflow")
	}
	msg.StreamID = binary.BigEndian.Uint32(data[:4])
	data = data[4:]
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: StreamData.Seq overflow")
	}
	msg.Seq = binary.BigEndian.Uint32(data[:4])
	data = data[4:]
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: StreamData.Ack overflow")
	}
	msg.Ack = binary.BigEndian.Uint32(data[:4])
	data = data[4:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: StreamData.Window overflow")
	}
	msg.Window = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: StreamData.PayloadLen overflow")
	}
	msg.PayloadLen = binary.BigEndian.Uint32(data[:4])
	data = data[4:]
	if uint64(msg.PayloadLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: StreamData.Payload overflow")
	}
	msg.Payload = append([]byte(nil), data[:uint64(msg.PayloadLen)]...)
	data = data[uint64(msg.PayloadLen):]
	_ = data
	return msg, nil
}

func marshalStreamAck(msg *StreamAck) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil StreamAck")
	}
	buf := make([]byte, 0)
	buf = appendUint32(buf, msg.StreamID)
	buf = appendUint32(buf, msg.Ack)
	buf = appendUint16(buf, msg.Credit)
	msg.SACKLen = uint16(len(msg.SACK))
	buf = appendUint16(buf, msg.SACKLen)
	buf = append(buf, msg.SACK...)
	return buf, nil
}

func unmarshalStreamAck(data []byte) (*StreamAck, error) {
	msg := &StreamAck{}
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: StreamAck.StreamID overflow")
	}
	msg.StreamID = binary.BigEndian.Uint32(data[:4])
	data = data[4:]
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: StreamAck.Ack overflow")
	}
	msg.Ack = binary.BigEndian.Uint32(data[:4])
	data = data[4:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: StreamAck.Credit overflow")
	}
	msg.Credit = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: StreamAck.SACKLen overflow")
	}
	msg.SACKLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.SACKLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: StreamAck.SACK overflow")
	}
	msg.SACK = append([]byte(nil), data[:uint64(msg.SACKLen)]...)
	data = data[uint64(msg.SACKLen):]
	_ = data
	return msg, nil
}

func marshalStreamClose(msg *StreamClose) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil StreamClose")
	}
	buf := make([]byte, 0)
	buf = appendUint32(buf, msg.StreamID)
	buf = appendUint16(buf, msg.Code)
	msg.ReasonLen = uint16(len(msg.Reason))
	buf = appendUint16(buf, msg.ReasonLen)
	buf = append(buf, []byte(msg.Reason)...)
	return buf, nil
}

func unmarshalStreamClose(data []byte) (*StreamClose, error) {
	msg := &StreamClose{}
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: StreamClose.StreamID overflow")
	}
	msg.StreamID = binary.BigEndian.Uint32(data[:4])
	data = data[4:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: StreamClose.Code overflow")
	}
	msg.Code = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: StreamClose.ReasonLen overflow")
	}
	msg.ReasonLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ReasonLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: StreamClose.Reason overflow")
	}
	msg.Reason = string(data[:uint64(msg.ReasonLen)])
	data = data[uint64(msg.ReasonLen):]
	_ = data
	return msg, nil
}

func marshalSleepUpdate(msg *SleepUpdate) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil SleepUpdate")
	}
	buf := make([]byte, 0)
	buf = appendUint16(buf, msg.Flags)
	buf = appendInt32(buf, msg.SleepSeconds)
	buf = appendInt32(buf, msg.WorkSeconds)
	buf = appendUint16(buf, msg.JitterPermille)
	return buf, nil
}

func unmarshalSleepUpdate(data []byte) (*SleepUpdate, error) {
	msg := &SleepUpdate{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SleepUpdate.Flags overflow")
	}
	msg.Flags = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: SleepUpdate.SleepSeconds overflow")
	}
	msg.SleepSeconds = int32(binary.BigEndian.Uint32(data[:4]))
	data = data[4:]
	if len(data) < 4 {
		return nil, fmt.Errorf("codec: SleepUpdate.WorkSeconds overflow")
	}
	msg.WorkSeconds = int32(binary.BigEndian.Uint32(data[:4]))
	data = data[4:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SleepUpdate.JitterPermille overflow")
	}
	msg.JitterPermille = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	_ = data
	return msg, nil
}

func marshalSleepUpdateAck(msg *SleepUpdateAck) ([]byte, error) {
	if msg == nil {
		return nil, fmt.Errorf("codec: nil SleepUpdateAck")
	}
	buf := make([]byte, 0)
	buf = appendUint16(buf, msg.OK)
	msg.ErrorLen = uint16(len(msg.Error))
	buf = appendUint16(buf, msg.ErrorLen)
	buf = append(buf, []byte(msg.Error)...)
	return buf, nil
}

func unmarshalSleepUpdateAck(data []byte) (*SleepUpdateAck, error) {
	msg := &SleepUpdateAck{}
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SleepUpdateAck.OK overflow")
	}
	msg.OK = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if len(data) < 2 {
		return nil, fmt.Errorf("codec: SleepUpdateAck.ErrorLen overflow")
	}
	msg.ErrorLen = binary.BigEndian.Uint16(data[:2])
	data = data[2:]
	if uint64(msg.ErrorLen) > uint64(len(data)) {
		return nil, fmt.Errorf("codec: SleepUpdateAck.Error overflow")
	}
	msg.Error = string(data[:uint64(msg.ErrorLen)])
	data = data[uint64(msg.ErrorLen):]
	_ = data
	return msg, nil
}

func marshalMessagePayload(msg interface{}) ([]byte, error) {
	switch m := msg.(type) {
	case *HIMess:
		return marshalHIMess(m)
	case *UUIDMess:
		return marshalUUIDMess(m)
	case *ChildUUIDReq:
		return marshalChildUUIDReq(m)
	case *ChildUUIDRes:
		return marshalChildUUIDRes(m)
	case *MyInfo:
		return marshalMyInfo(m)
	case *MyMemo:
		return marshalMyMemo(m)
	case *ListenReq:
		return marshalListenReq(m)
	case *ListenRes:
		return marshalListenRes(m)
	case *ListenStop:
		return marshalListenStop(m)
	case *ConnectStart:
		return marshalConnectStart(m)
	case *ConnectDone:
		return marshalConnectDone(m)
	case *NodeConnInfo:
		return marshalNodeConnInfo(m)
	case *NodeOffline:
		return marshalNodeOffline(m)
	case *NodeReonline:
		return marshalNodeReonline(m)
	case *UpstreamOffline:
		return marshalUpstreamOffline(m)
	case *UpstreamReonline:
		return marshalUpstreamReonline(m)
	case *Shutdown:
		return marshalShutdown(m)
	case *HeartbeatMsg:
		return marshalHeartbeatMsg(m)
	case *RuntimeLog:
		return marshalRuntimeLog(m)
	case *GossipUpdate:
		return marshalGossipUpdate(m)
	case *GossipRequest:
		return marshalGossipRequest(m)
	case *GossipResponse:
		return marshalGossipResponse(m)
	case *GossipDiscover:
		return marshalGossipDiscover(m)
	case *GossipHeartbeat:
		return marshalGossipHeartbeat(m)
	case *GossipRouteUpdate:
		return marshalGossipRouteUpdate(m)
	case *GossipNodeJoin:
		return marshalGossipNodeJoin(m)
	case *GossipNodeLeave:
		return marshalGossipNodeLeave(m)
	case *SuppLinkRequest:
		return marshalSuppLinkRequest(m)
	case *SuppLinkResponse:
		return marshalSuppLinkResponse(m)
	case *SuppLinkTeardown:
		return marshalSuppLinkTeardown(m)
	case *SuppLinkHeartbeat:
		return marshalSuppLinkHeartbeat(m)
	case *SuppFailoverCommand:
		return marshalSuppFailoverCommand(m)
	case *SuppLinkPromote:
		return marshalSuppLinkPromote(m)
	case *RescueRequest:
		return marshalRescueRequest(m)
	case *RescueResponse:
		return marshalRescueResponse(m)
	case *DTNData:
		return marshalDTNData(m)
	case *DTNAck:
		return marshalDTNAck(m)
	case *DTNPull:
		return marshalDTNPull(m)
	case *StreamOpen:
		return marshalStreamOpen(m)
	case *StreamData:
		return marshalStreamData(m)
	case *StreamAck:
		return marshalStreamAck(m)
	case *StreamClose:
		return marshalStreamClose(m)
	case *SleepUpdate:
		return marshalSleepUpdate(m)
	case *SleepUpdateAck:
		return marshalSleepUpdateAck(m)
	default:
		return nil, fmt.Errorf("codec: unsupported message %T", msg)
	}
}

func unmarshalMessagePayload(messageType uint16, data []byte) (interface{}, error) {
	switch messageType {
	case HI:
		return unmarshalHIMess(data)
	case UUID:
		return unmarshalUUIDMess(data)
	case CHILDUUIDREQ:
		return unmarshalChildUUIDReq(data)
	case CHILDUUIDRES:
		return unmarshalChildUUIDRes(data)
	case MYINFO:
		return unmarshalMyInfo(data)
	case MYMEMO:
		return unmarshalMyMemo(data)
	case LISTENREQ:
		return unmarshalListenReq(data)
	case LISTENRES:
		return unmarshalListenRes(data)
	case LISTENSTOP:
		return unmarshalListenStop(data)
	case CONNECTSTART:
		return unmarshalConnectStart(data)
	case CONNECTDONE:
		return unmarshalConnectDone(data)
	case NODECONNINFO:
		return unmarshalNodeConnInfo(data)
	case NODEOFFLINE:
		return unmarshalNodeOffline(data)
	case NODEREONLINE:
		return unmarshalNodeReonline(data)
	case UPSTREAMOFFLINE:
		return unmarshalUpstreamOffline(data)
	case UPSTREAMREONLINE:
		return unmarshalUpstreamReonline(data)
	case SHUTDOWN:
		return unmarshalShutdown(data)
	case HEARTBEAT:
		return unmarshalHeartbeatMsg(data)
	case RUNTIMELOG:
		return unmarshalRuntimeLog(data)
	case GOSSIP_UPDATE:
		return unmarshalGossipUpdate(data)
	case GOSSIP_REQUEST:
		return unmarshalGossipRequest(data)
	case GOSSIP_RESPONSE:
		return unmarshalGossipResponse(data)
	case GOSSIP_DISCOVER:
		return unmarshalGossipDiscover(data)
	case GOSSIP_HEARTBEAT:
		return unmarshalGossipHeartbeat(data)
	case GOSSIP_ROUTE_UPDATE:
		return unmarshalGossipRouteUpdate(data)
	case GOSSIP_NODE_JOIN:
		return unmarshalGossipNodeJoin(data)
	case GOSSIP_NODE_LEAVE:
		return unmarshalGossipNodeLeave(data)
	case SUPPLINKREQ:
		return unmarshalSuppLinkRequest(data)
	case SUPPLINKRESP:
		return unmarshalSuppLinkResponse(data)
	case SUPPLINKTEARDOWN:
		return unmarshalSuppLinkTeardown(data)
	case SUPPLINKHEARTBEAT:
		return unmarshalSuppLinkHeartbeat(data)
	case SUPPFAILOVER:
		return unmarshalSuppFailoverCommand(data)
	case SUPPLINKPROMOTE:
		return unmarshalSuppLinkPromote(data)
	case RESCUE_REQUEST:
		return unmarshalRescueRequest(data)
	case RESCUE_RESPONSE:
		return unmarshalRescueResponse(data)
	case DTN_DATA:
		return unmarshalDTNData(data)
	case DTN_ACK:
		return unmarshalDTNAck(data)
	case DTN_PULL:
		return unmarshalDTNPull(data)
	case STREAM_OPEN:
		return unmarshalStreamOpen(data)
	case STREAM_DATA:
		return unmarshalStreamData(data)
	case STREAM_ACK:
		return unmarshalStreamAck(data)
	case STREAM_CLOSE:
		return unmarshalStreamClose(data)
	case SLEEP_UPDATE:
		return unmarshalSleepUpdate(data)
	case SLEEP_UPDATE_ACK:
		return unmarshalSleepUpdateAck(data)
	default:
		return nil, fmt.Errorf("codec: unsupported message type %d", messageType)
	}
}
