// Code generated by gencodec; DO NOT EDIT.
package protocol

import (
	"reflect"
	"testing"
)

func newSampleHIMess() interface{} {
	msg := &HIMess{}
	msg.Greeting = "greeting-value"
	msg.GreetingLen = uint16(len(msg.Greeting))
	msg.UUID = "uuid-value"
	msg.UUIDLen = uint16(len(msg.UUID))
	msg.IsAdmin = 1
	msg.IsReconnect = 1
	msg.ProtoFlags = 1
	return msg
}

func newSampleUUIDMess() interface{} {
	msg := &UUIDMess{}
	msg.UUID = "uuid-value"
	msg.UUIDLen = uint16(len(msg.UUID))
	msg.ProtoFlags = 1
	return msg
}

func newSampleChildUUIDReq() interface{} {
	msg := &ChildUUIDReq{}
	msg.ParentUUID = "parentuuid-value"
	msg.ParentUUIDLen = uint16(len(msg.ParentUUID))
	msg.IP = "ip-value"
	msg.IPLen = uint16(len(msg.IP))
	msg.RequestID = "requestid-value"
	msg.RequestIDLen = uint16(len(msg.RequestID))
	return msg
}

func newSampleChildUUIDRes() interface{} {
	msg := &ChildUUIDRes{}
	msg.UUID = "uuid-value"
	msg.UUIDLen = uint16(len(msg.UUID))
	msg.RequestID = "requestid-value"
	msg.RequestIDLen = uint16(len(msg.RequestID))
	return msg
}

func newSampleMyInfo() interface{} {
	msg := &MyInfo{}
	msg.UUID = "uuid-value"
	msg.UUIDLen = uint16(len(msg.UUID))
	msg.Username = "username-value"
	msg.UsernameLen = uint64(len(msg.Username))
	msg.Hostname = "hostname-value"
	msg.HostnameLen = uint64(len(msg.Hostname))
	msg.Memo = "memo-value"
	msg.MemoLen = uint64(len(msg.Memo))
	return msg
}

func newSampleMyMemo() interface{} {
	msg := &MyMemo{}
	msg.Memo = "memo-value"
	msg.MemoLen = uint64(len(msg.Memo))
	return msg
}

func newSampleListenReq() interface{} {
	msg := &ListenReq{}
	msg.Method = 1
	msg.Addr = "addr-value"
	msg.AddrLen = uint64(len(msg.Addr))
	msg.ListenerID = "listenerid-value"
	msg.ListenerIDLen = uint16(len(msg.ListenerID))
	return msg
}

func newSampleListenRes() interface{} {
	msg := &ListenRes{}
	msg.OK = 1
	msg.ListenerID = "listenerid-value"
	msg.ListenerIDLen = uint16(len(msg.ListenerID))
	return msg
}

func newSampleListenStop() interface{} {
	msg := &ListenStop{}
	msg.ListenerID = "listenerid-value"
	msg.ListenerIDLen = uint16(len(msg.ListenerID))
	return msg
}

func newSampleConnectStart() interface{} {
	msg := &ConnectStart{}
	msg.Addr = "addr-value"
	msg.AddrLen = uint16(len(msg.Addr))
	return msg
}

func newSampleConnectDone() interface{} {
	msg := &ConnectDone{}
	msg.OK = 1
	return msg
}

func newSampleNodeConnInfo() interface{} {
	msg := &NodeConnInfo{}
	msg.UUID = "uuid-value"
	msg.UUIDLen = uint16(len(msg.UUID))
	msg.DialAddress = "dialaddress-value"
	msg.DialAddrLen = uint16(len(msg.DialAddress))
	msg.ListenPort = 1
	msg.FallbackPort = 1
	msg.Transport = "transport-value"
	msg.TransportLen = uint16(len(msg.Transport))
	msg.TlsEnabled = 1
	msg.LastSuccessUnix = int64(5)
	return msg
}

func newSampleNodeOffline() interface{} {
	msg := &NodeOffline{}
	msg.UUID = "uuid-value"
	msg.UUIDLen = uint16(len(msg.UUID))
	return msg
}

func newSampleNodeReonline() interface{} {
	msg := &NodeReonline{}
	msg.ParentUUID = "parentuuid-value"
	msg.ParentUUIDLen = uint16(len(msg.ParentUUID))
	msg.UUID = "uuid-value"
	msg.UUIDLen = uint16(len(msg.UUID))
	msg.IP = "ip-value"
	msg.IPLen = uint16(len(msg.IP))
	return msg
}

func newSampleUpstreamOffline() interface{} {
	msg := &UpstreamOffline{}
	msg.OK = 1
	return msg
}

func newSampleUpstreamReonline() interface{} {
	msg := &UpstreamReonline{}
	msg.OK = 1
	return msg
}

func newSampleShutdown() interface{} {
	msg := &Shutdown{}
	msg.OK = 1
	return msg
}

func newSampleHeartbeatMsg() interface{} {
	msg := &HeartbeatMsg{}
	msg.Ping = 1
	return msg
}

func newSampleRuntimeLog() interface{} {
	msg := &RuntimeLog{}
	msg.UUID = "uuid-value"
	msg.UUIDLen = uint16(len(msg.UUID))
	msg.Severity = "severity-value"
	msg.SeverityLen = uint16(len(msg.Severity))
	msg.Code = "code-value"
	msg.CodeLen = uint16(len(msg.Code))
	msg.Message = "message-value"
	msg.MessageLen = uint64(len(msg.Message))
	msg.Retryable = 1
	msg.Cause = "cause-value"
	msg.CauseLen = uint64(len(msg.Cause))
	return msg
}

func newSampleGossipUpdate() interface{} {
	msg := &GossipUpdate{}
	msg.TTL = int32(4)
	msg.NodeData = []byte{0x01, 0x02, 0x03}
	msg.NodeDataLen = uint64(len(msg.NodeData))
	msg.SenderUUID = "senderuuid-value"
	msg.SenderUUIDLen = uint16(len(msg.SenderUUID))
	msg.Timestamp = int64(5)
	return msg
}

func newSampleGossipRequest() interface{} {
	msg := &GossipRequest{}
	msg.RequestUUID = "requestuuid-value"
	msg.RequestUUIDLen = uint16(len(msg.RequestUUID))
	msg.RequesterUUID = "requesteruuid-value"
	msg.RequesterUUIDLen = uint16(len(msg.RequesterUUID))
	msg.TargetUUID = "targetuuid-value"
	msg.TargetUUIDLen = uint16(len(msg.TargetUUID))
	msg.Timestamp = int64(5)
	return msg
}

func newSampleGossipResponse() interface{} {
	msg := &GossipResponse{}
	msg.RequestUUID = "requestuuid-value"
	msg.RequestUUIDLen = uint16(len(msg.RequestUUID))
	msg.RequesterUUID = "requesteruuid-value"
	msg.RequesterUUIDLen = uint16(len(msg.RequesterUUID))
	msg.ResponderUUID = "responderuuid-value"
	msg.ResponderUUIDLen = uint16(len(msg.ResponderUUID))
	msg.TargetUUID = "targetuuid-value"
	msg.TargetUUIDLen = uint16(len(msg.TargetUUID))
	msg.Reachable = true
	msg.Latency = int64(5)
	msg.NodeData = []byte{0x01, 0x02, 0x03}
	msg.NodeDataLen = uint64(len(msg.NodeData))
	msg.Timestamp = int64(5)
	return msg
}

func newSampleGossipDiscover() interface{} {
	msg := &GossipDiscover{}
	msg.SenderUUID = "senderuuid-value"
	msg.SenderUUIDLen = uint16(len(msg.SenderUUID))
	msg.SenderIP = "senderip-value"
	msg.SenderIPLen = uint16(len(msg.SenderIP))
	msg.SenderPort = 1
	msg.Timestamp = int64(5)
	return msg
}

func newSampleGossipHeartbeat() interface{} {
	msg := &GossipHeartbeat{}
	msg.SenderUUID = "senderuuid-value"
	msg.SenderUUIDLen = uint16(len(msg.SenderUUID))
	msg.Status = int32(4)
	msg.Load = int32(4)
	msg.Timestamp = int64(5)
	return msg
}

func newSampleGossipRouteUpdate() interface{} {
	msg := &GossipRouteUpdate{}
	msg.SenderUUID = "senderuuid-value"
	msg.SenderUUIDLen = uint16(len(msg.SenderUUID))
	msg.TargetUUID = "targetuuid-value"
	msg.TargetUUIDLen = uint16(len(msg.TargetUUID))
	msg.NextHopUUID = "nexthopuuid-value"
	msg.NextHopUUIDLen = uint16(len(msg.NextHopUUID))
	msg.HopCount = int32(4)
	msg.Weight = int32(4)
	msg.IsReachable = true
	msg.Timestamp = int64(5)
	return msg
}

func newSampleGossipNodeJoin() interface{} {
	msg := &GossipNodeJoin{}
	msg.NodeUUID = "nodeuuid-value"
	msg.NodeUUIDLen = uint16(len(msg.NodeUUID))
	msg.NodeIP = "nodeip-value"
	msg.NodeIPLen = uint16(len(msg.NodeIP))
	msg.NodePort = 1
	msg.ParentUUID = "parentuuid-value"
	msg.ParentUUIDLen = uint16(len(msg.ParentUUID))
	msg.Timestamp = int64(5)
	return msg
}

func newSampleGossipNodeLeave() interface{} {
	msg := &GossipNodeLeave{}
	msg.NodeUUID = "nodeuuid-value"
	msg.NodeUUIDLen = uint16(len(msg.NodeUUID))
	msg.Reason = int32(4)
	msg.Timestamp = int64(5)
	return msg
}

func newSampleSuppLinkRequest() interface{} {
	msg := &SuppLinkRequest{}
	msg.RequestUUID = "requestuuid-value"
	msg.RequestUUIDLen = uint16(len(msg.RequestUUID))
	msg.LinkUUID = "linkuuid-value"
	msg.LinkUUIDLen = uint16(len(msg.LinkUUID))
	msg.InitiatorUUID = "initiatoruuid-value"
	msg.InitiatorUUIDLen = uint16(len(msg.InitiatorUUID))
	msg.TargetUUID = "targetuuid-value"
	msg.TargetUUIDLen = uint16(len(msg.TargetUUID))
	msg.PeerIP = "peerip-value"
	msg.PeerIPLen = uint16(len(msg.PeerIP))
	msg.PeerPort = 1
	msg.Action = 1
	msg.Role = 1
	msg.Flags = 1
	msg.Timeout = 2
	return msg
}

func newSampleSuppLinkResponse() interface{} {
	msg := &SuppLinkResponse{}
	msg.RequestUUID = "requestuuid-value"
	msg.RequestUUIDLen = uint16(len(msg.RequestUUID))
	msg.LinkUUID = "linkuuid-value"
	msg.LinkUUIDLen = uint16(len(msg.LinkUUID))
	msg.AgentUUID = "agentuuid-value"
	msg.AgentUUIDLen = uint16(len(msg.AgentUUID))
	msg.PeerUUID = "peeruuid-value"
	msg.PeerUUIDLen = uint16(len(msg.PeerUUID))
	msg.Role = 1
	msg.Status = 1
	msg.Message = "message-value"
	msg.MessageLen = uint16(len(msg.Message))
	msg.ListenIP = "listenip-value"
	msg.ListenIPLen = uint16(len(msg.ListenIP))
	msg.ListenPort = 1
	return msg
}

func newSampleSuppLinkTeardown() interface{} {
	msg := &SuppLinkTeardown{}
	msg.LinkUUID = "linkuuid-value"
	msg.LinkUUIDLen = uint16(len(msg.LinkUUID))
	msg.Reason = "reason-value"
	msg.ReasonLen = uint16(len(msg.Reason))
	return msg
}

func newSampleSuppLinkHeartbeat() interface{} {
	msg := &SuppLinkHeartbeat{}
	msg.LinkUUID = "linkuuid-value"
	msg.LinkUUIDLen = uint16(len(msg.LinkUUID))
	msg.PeerUUID = "peeruuid-value"
	msg.PeerUUIDLen = uint16(len(msg.PeerUUID))
	msg.Status = 1
	msg.Timestamp = int64(5)
	return msg
}

func newSampleSuppFailoverCommand() interface{} {
	msg := &SuppFailoverCommand{}
	msg.LinkUUID = "linkuuid-value"
	msg.LinkUUIDLen = uint16(len(msg.LinkUUID))
	msg.ParentUUID = "parentuuid-value"
	msg.ParentUUIDLen = uint16(len(msg.ParentUUID))
	msg.ChildUUID = "childuuid-value"
	msg.ChildUUIDLen = uint16(len(msg.ChildUUID))
	msg.Role = 1
	msg.Flags = 1
	return msg
}

func newSampleSuppLinkPromote() interface{} {
	msg := &SuppLinkPromote{}
	msg.LinkUUID = "linkuuid-value"
	msg.LinkUUIDLen = uint16(len(msg.LinkUUID))
	msg.ParentUUID = "parentuuid-value"
	msg.ParentUUIDLen = uint16(len(msg.ParentUUID))
	msg.ChildUUID = "childuuid-value"
	msg.ChildUUIDLen = uint16(len(msg.ChildUUID))
	msg.Role = 1
	return msg
}

func newSampleRescueRequest() interface{} {
	msg := &RescueRequest{}
	msg.TargetUUID = "targetuuid-value"
	msg.TargetUUIDLen = uint16(len(msg.TargetUUID))
	msg.DialAddr = "dialaddr-value"
	msg.DialAddrLen = uint16(len(msg.DialAddr))
	msg.DialPort = 1
	msg.Transport = "transport-value"
	msg.TransportLen = uint16(len(msg.Transport))
	msg.Secret = "secret-value"
	msg.SecretLen = uint16(len(msg.Secret))
	msg.Flags = 1
	return msg
}

func newSampleRescueResponse() interface{} {
	msg := &RescueResponse{}
	msg.TargetUUID = "targetuuid-value"
	msg.TargetUUIDLen = uint16(len(msg.TargetUUID))
	msg.RescuerUUID = "rescueruuid-value"
	msg.RescuerUUIDLen = uint16(len(msg.RescuerUUID))
	msg.Status = 1
	msg.Message = "message-value"
	msg.MessageLen = uint16(len(msg.Message))
	msg.ParentUUID = "parentuuid-value"
	msg.ParentUUIDLen = uint16(len(msg.ParentUUID))
	msg.ChildUUID = "childuuid-value"
	msg.ChildUUIDLen = uint16(len(msg.ChildUUID))
	return msg
}

func newSampleDTNData() interface{} {
	msg := &DTNData{}
	msg.BundleID = "bundleid-value"
	msg.BundleIDLen = uint16(len(msg.BundleID))
	msg.Payload = []byte{0x01, 0x02, 0x03}
	msg.PayloadLen = uint64(len(msg.Payload))
	return msg
}

func newSampleDTNAck() interface{} {
	msg := &DTNAck{}
	msg.BundleID = "bundleid-value"
	msg.BundleIDLen = uint16(len(msg.BundleID))
	msg.OK = 1
	msg.Error = "error-value"
	msg.ErrorLen = uint16(len(msg.Error))
	return msg
}

func newSampleDTNPull() interface{} {
	msg := &DTNPull{}
	msg.Limit = 1
	return msg
}

func newSampleStreamOpen() interface{} {
	msg := &StreamOpen{}
	msg.StreamID = 2
	msg.Options = "options-value"
	msg.OptionsLen = uint16(len(msg.Options))
	return msg
}

func newSampleStreamData() interface{} {
	msg := &StreamData{}
	msg.StreamID = 2
	msg.Seq = 2
	msg.Ack = 2
	msg.Window = 1
	msg.Payload = []byte{0x01, 0x02, 0x03}
	msg.PayloadLen = uint32(len(msg.Payload))
	return msg
}

func newSampleStreamAck() interface{} {
	msg := &StreamAck{}
	msg.StreamID = 2
	msg.Ack = 2
	msg.Credit = 1
	msg.SACK = []byte{0x01, 0x02, 0x03}
	msg.SACKLen = uint16(len(msg.SACK))
	return msg
}

func newSampleStreamClose() interface{} {
	msg := &StreamClose{}
	msg.StreamID = 2
	msg.Code = 1
	msg.Reason = "reason-value"
	msg.ReasonLen = uint16(len(msg.Reason))
	return msg
}

func newSampleSleepUpdate() interface{} {
	msg := &SleepUpdate{}
	msg.Flags = 1
	msg.SleepSeconds = int32(4)
	msg.WorkSeconds = int32(4)
	msg.JitterPermille = 1
	return msg
}

func newSampleSleepUpdateAck() interface{} {
	msg := &SleepUpdateAck{}
	msg.OK = 1
	msg.Error = "error-value"
	msg.ErrorLen = uint16(len(msg.Error))
	return msg
}

func TestMessageCodecRoundTrip(t *testing.T) {
	tests := []struct {
		name        string
		constructor func() interface{}
	}{}
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "HIMess",
		constructor: func() interface{} { return newSampleHIMess() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "UUIDMess",
		constructor: func() interface{} { return newSampleUUIDMess() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "ChildUUIDReq",
		constructor: func() interface{} { return newSampleChildUUIDReq() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "ChildUUIDRes",
		constructor: func() interface{} { return newSampleChildUUIDRes() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "MyInfo",
		constructor: func() interface{} { return newSampleMyInfo() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "MyMemo",
		constructor: func() interface{} { return newSampleMyMemo() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "ListenReq",
		constructor: func() interface{} { return newSampleListenReq() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "ListenRes",
		constructor: func() interface{} { return newSampleListenRes() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "ListenStop",
		constructor: func() interface{} { return newSampleListenStop() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "ConnectStart",
		constructor: func() interface{} { return newSampleConnectStart() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "ConnectDone",
		constructor: func() interface{} { return newSampleConnectDone() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "NodeConnInfo",
		constructor: func() interface{} { return newSampleNodeConnInfo() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "NodeOffline",
		constructor: func() interface{} { return newSampleNodeOffline() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "NodeReonline",
		constructor: func() interface{} { return newSampleNodeReonline() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "UpstreamOffline",
		constructor: func() interface{} { return newSampleUpstreamOffline() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "UpstreamReonline",
		constructor: func() interface{} { return newSampleUpstreamReonline() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "Shutdown",
		constructor: func() interface{} { return newSampleShutdown() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "HeartbeatMsg",
		constructor: func() interface{} { return newSampleHeartbeatMsg() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "RuntimeLog",
		constructor: func() interface{} { return newSampleRuntimeLog() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "GossipUpdate",
		constructor: func() interface{} { return newSampleGossipUpdate() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "GossipRequest",
		constructor: func() interface{} { return newSampleGossipRequest() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "GossipResponse",
		constructor: func() interface{} { return newSampleGossipResponse() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "GossipDiscover",
		constructor: func() interface{} { return newSampleGossipDiscover() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "GossipHeartbeat",
		constructor: func() interface{} { return newSampleGossipHeartbeat() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "GossipRouteUpdate",
		constructor: func() interface{} { return newSampleGossipRouteUpdate() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "GossipNodeJoin",
		constructor: func() interface{} { return newSampleGossipNodeJoin() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "GossipNodeLeave",
		constructor: func() interface{} { return newSampleGossipNodeLeave() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "SuppLinkRequest",
		constructor: func() interface{} { return newSampleSuppLinkRequest() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "SuppLinkResponse",
		constructor: func() interface{} { return newSampleSuppLinkResponse() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "SuppLinkTeardown",
		constructor: func() interface{} { return newSampleSuppLinkTeardown() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "SuppLinkHeartbeat",
		constructor: func() interface{} { return newSampleSuppLinkHeartbeat() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "SuppFailoverCommand",
		constructor: func() interface{} { return newSampleSuppFailoverCommand() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "SuppLinkPromote",
		constructor: func() interface{} { return newSampleSuppLinkPromote() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "RescueRequest",
		constructor: func() interface{} { return newSampleRescueRequest() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "RescueResponse",
		constructor: func() interface{} { return newSampleRescueResponse() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "DTNData",
		constructor: func() interface{} { return newSampleDTNData() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "DTNAck",
		constructor: func() interface{} { return newSampleDTNAck() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "DTNPull",
		constructor: func() interface{} { return newSampleDTNPull() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "StreamOpen",
		constructor: func() interface{} { return newSampleStreamOpen() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "StreamData",
		constructor: func() interface{} { return newSampleStreamData() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "StreamAck",
		constructor: func() interface{} { return newSampleStreamAck() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "StreamClose",
		constructor: func() interface{} { return newSampleStreamClose() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "SleepUpdate",
		constructor: func() interface{} { return newSampleSleepUpdate() },
	})
	tests = append(tests, struct {
		name        string
		constructor func() interface{}
	}{
		name:        "SleepUpdateAck",
		constructor: func() interface{} { return newSampleSleepUpdateAck() },
	})
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			msg := tt.constructor()
			data, err := marshalMessagePayload(msg)
			if err != nil {
				t.Fatalf("marshal failed: %v", err)
			}
			decoded, err := unmarshalMessagePayload(messageTypeFor(msg), data)
			if err != nil {
				t.Fatalf("unmarshal failed: %v", err)
			}
			if !reflect.DeepEqual(msg, decoded) {
				t.Fatalf("round trip mismatch: %v vs %v", msg, decoded)
			}
		})
	}
}

func messageTypeFor(msg interface{}) uint16 {
	switch msg.(type) {
	case *HIMess:
		return HI
	case *UUIDMess:
		return UUID
	case *ChildUUIDReq:
		return CHILDUUIDREQ
	case *ChildUUIDRes:
		return CHILDUUIDRES
	case *MyInfo:
		return MYINFO
	case *MyMemo:
		return MYMEMO
	case *ListenReq:
		return LISTENREQ
	case *ListenRes:
		return LISTENRES
	case *ListenStop:
		return LISTENSTOP
	case *ConnectStart:
		return CONNECTSTART
	case *ConnectDone:
		return CONNECTDONE
	case *NodeConnInfo:
		return NODECONNINFO
	case *NodeOffline:
		return NODEOFFLINE
	case *NodeReonline:
		return NODEREONLINE
	case *UpstreamOffline:
		return UPSTREAMOFFLINE
	case *UpstreamReonline:
		return UPSTREAMREONLINE
	case *Shutdown:
		return SHUTDOWN
	case *HeartbeatMsg:
		return HEARTBEAT
	case *RuntimeLog:
		return RUNTIMELOG
	case *GossipUpdate:
		return GOSSIP_UPDATE
	case *GossipRequest:
		return GOSSIP_REQUEST
	case *GossipResponse:
		return GOSSIP_RESPONSE
	case *GossipDiscover:
		return GOSSIP_DISCOVER
	case *GossipHeartbeat:
		return GOSSIP_HEARTBEAT
	case *GossipRouteUpdate:
		return GOSSIP_ROUTE_UPDATE
	case *GossipNodeJoin:
		return GOSSIP_NODE_JOIN
	case *GossipNodeLeave:
		return GOSSIP_NODE_LEAVE
	case *SuppLinkRequest:
		return SUPPLINKREQ
	case *SuppLinkResponse:
		return SUPPLINKRESP
	case *SuppLinkTeardown:
		return SUPPLINKTEARDOWN
	case *SuppLinkHeartbeat:
		return SUPPLINKHEARTBEAT
	case *SuppFailoverCommand:
		return SUPPFAILOVER
	case *SuppLinkPromote:
		return SUPPLINKPROMOTE
	case *RescueRequest:
		return RESCUE_REQUEST
	case *RescueResponse:
		return RESCUE_RESPONSE
	case *DTNData:
		return DTN_DATA
	case *DTNAck:
		return DTN_ACK
	case *DTNPull:
		return DTN_PULL
	case *StreamOpen:
		return STREAM_OPEN
	case *StreamData:
		return STREAM_DATA
	case *StreamAck:
		return STREAM_ACK
	case *StreamClose:
		return STREAM_CLOSE
	case *SleepUpdate:
		return SLEEP_UPDATE
	case *SleepUpdateAck:
		return SLEEP_UPDATE_ACK
	default:
		return 0
	}
}
