// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * API 是绑定给前端（Wails）的门面对象。所有由 Vue 组件发起的调用都会经过这里。
 *
 * 线程模型：
 *   - Wails 可能在多个 goroutine 里调用方法，mu 用于保护 client/stream 字段。
 *   - EventStream goroutine 独立运行，通过 Hooks.Emit 推送事件给前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kelpie$0 from "../kelpie/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseInteractiveStream(req: $models.CloseInteractiveStreamRequest): $CancellablePromise<void> {
    return $Call.ByID(1352431101, req);
}

export function CloseStreamByID(req: $models.CloseStreamByIDRequest): $CancellablePromise<void> {
    return $Call.ByID(3637656403, req);
}

export function CollectRemoteFile(req: $models.CollectRemoteFileRequest): $CancellablePromise<$models.CollectRemoteFileResult> {
    return $Call.ByID(2257100417, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Connect 尝试连接 Kelpie。语义：
 *   - 未开启 TLS：直接 dial。
 *   - 开启 TLS：按 TOFU 查本地指纹，若空则首次握手并返回 PhaseAwaitingTrust；
 *     用户同意后再次调用时设置 req.ForceAccept=true，此时会保存指纹并重试。
 */
export function Connect(req: $models.ConnectRequest): $CancellablePromise<$models.ConnectResult> {
    return $Call.ByID(3556273313, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateControllerListener(req: $models.ListenerSpecRequest): $CancellablePromise<$models.ControllerListenerDTO> {
    return $Call.ByID(3067463861, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CreatePivotListener(req: $models.ListenerSpecRequest): $CancellablePromise<$models.PivotListenerDTO> {
    return $Call.ByID(1377126039, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function DeleteControllerListener(req: $models.ListenerSpecRequest): $CancellablePromise<$models.ControllerListenerDTO> {
    return $Call.ByID(2056017750, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeletePivotListener(req: $models.ListenerSpecRequest): $CancellablePromise<void> {
    return $Call.ByID(767321046, req);
}

/**
 * Disconnect 主动断开，不删除 TOFU 指纹。
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(3977418323);
}

/**
 * EnqueueDTN 发一条 DTN payload。
 */
export function EnqueueDTN(req: $models.EnqueueDTNRequest): $CancellablePromise<$models.EnqueueDTNResult> {
    return $Call.ByID(428641969, req).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ExportLoot(req: $models.ExportLootRequest): $CancellablePromise<$models.ExportLootResult> {
    return $Call.ByID(3945664357, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ForgetFingerprint 让 UI 能"忘记信任"。
 */
export function ForgetFingerprint(endpoint: string): $CancellablePromise<void> {
    return $Call.ByID(3453954416, endpoint);
}

/**
 * GetConnectionStatus 给前端查询当前连接状态。
 */
export function GetConnectionStatus(): $CancellablePromise<$models.ConnectionStatus> {
    return $Call.ByID(1035792753).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetMetrics 取聚合指标。
 */
export function GetMetrics(): $CancellablePromise<$models.MetricsDTO> {
    return $Call.ByID(1795647200).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetSessionDiagnostics(req: $models.SessionActionRequest): $CancellablePromise<$models.SessionDiagnosticsDTO> {
    return $Call.ByID(2815672379, req).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetSnapshot 取当前拓扑、会话、sleep 一份快照（用于 UI 初始化/手动刷新）。
 */
export function GetSnapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(1002996951).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListControllerListeners(): $CancellablePromise<$models.ControllerListenerDTO[]> {
    return $Call.ByID(3191576286).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListLoot(req: $models.ListLootRequest): $CancellablePromise<$models.ListLootResult> {
    return $Call.ByID(3095836699, req).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListPivotListeners(req: $models.ListPivotListenersRequest): $CancellablePromise<$models.PivotListenerDTO[]> {
    return $Call.ByID(322590944, req).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ListRecentConnections 返回最近连接历史。
 */
export function ListRecentConnections(): $CancellablePromise<$models.RecentConnectionDTO[]> {
    return $Call.ByID(1862843263).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ListRemoteFiles(req: $models.ListRemoteFilesRequest): $CancellablePromise<$models.RemoteFileListingDTO> {
    return $Call.ByID(3890572326, req).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * ListSupplementalEvents 查最近 N 条补链事件。
 */
export function ListSupplementalEvents(limit: number): $CancellablePromise<$models.SupplementalEventDTO[]> {
    return $Call.ByID(1425965798, limit).then(($result: any) => {
        return $$createType17($result);
    });
}

export function MarkSession(req: $models.SessionActionRequest): $CancellablePromise<$models.SessionActionResult> {
    return $Call.ByID(1788566804, req).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * PruneOffline 清理离线节点。
 */
export function PruneOffline(): $CancellablePromise<$models.PruneOfflineResult> {
    return $Call.ByID(893042766).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * RecentEvents 供前端在首次进入时拉一段历史（ring buffer，最多 eventRingCap 条）。
 */
export function RecentEvents(limit: number): $CancellablePromise<kelpie$0.Event[]> {
    return $Call.ByID(1184302659, limit).then(($result: any) => {
        return $$createType21($result);
    });
}

export function ReconnectSession(req: $models.SessionActionRequest): $CancellablePromise<$models.SessionActionResult> {
    return $Call.ByID(1581020610, req).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * RemoveRecentConnection 删除一条历史。
 */
export function RemoveRecentConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(815435546, id);
}

export function RepairSession(req: $models.SessionActionRequest): $CancellablePromise<$models.SessionActionResult> {
    return $Call.ByID(3350380104, req).then(($result: any) => {
        return $$createType18($result);
    });
}

export function ResizeStream(req: $models.StreamResizeRequest): $CancellablePromise<void> {
    return $Call.ByID(2818048145, req);
}

export function SendStreamData(req: $models.StreamDataRequest): $CancellablePromise<void> {
    return $Call.ByID(3475283647, req);
}

export function StartBackwardProxy(req: $models.StartBackwardProxyRequest): $CancellablePromise<$models.StartBackwardProxyResult> {
    return $Call.ByID(3796921190, req).then(($result: any) => {
        return $$createType22($result);
    });
}

export function StartForwardProxy(req: $models.StartForwardProxyRequest): $CancellablePromise<$models.StartForwardProxyResult> {
    return $Call.ByID(4260703924, req).then(($result: any) => {
        return $$createType23($result);
    });
}

export function StartShell(req: $models.StartShellRequest): $CancellablePromise<$models.StreamHandleDTO> {
    return $Call.ByID(1583231979, req).then(($result: any) => {
        return $$createType24($result);
    });
}

export function StartSocksProxy(req: $models.StartSocksProxyRequest): $CancellablePromise<$models.StreamHandleDTO> {
    return $Call.ByID(3840580468, req).then(($result: any) => {
        return $$createType24($result);
    });
}

export function StartSshSession(req: $models.StartSshSessionRequest): $CancellablePromise<$models.StreamHandleDTO> {
    return $Call.ByID(641130889, req).then(($result: any) => {
        return $$createType24($result);
    });
}

export function StartSshTunnel(req: $models.StartSshTunnelRequest): $CancellablePromise<void> {
    return $Call.ByID(1569834321, req);
}

export function StopBackwardProxy(req: $models.StopBackwardProxyRequest): $CancellablePromise<$models.StopBackwardProxyResult> {
    return $Call.ByID(1467442300, req).then(($result: any) => {
        return $$createType25($result);
    });
}

export function StopForwardProxy(req: $models.StopForwardProxyRequest): $CancellablePromise<$models.StopForwardProxyResult> {
    return $Call.ByID(2557801326, req).then(($result: any) => {
        return $$createType26($result);
    });
}

export function StreamDiagnostics(): $CancellablePromise<$models.StreamDiagDTO[]> {
    return $Call.ByID(3271607167).then(($result: any) => {
        return $$createType28($result);
    });
}

export function StreamPing(req: $models.StreamPingRequest): $CancellablePromise<void> {
    return $Call.ByID(422845249, req);
}

export function TerminateSession(req: $models.SessionActionRequest): $CancellablePromise<$models.SessionActionResult> {
    return $Call.ByID(2083038568, req).then(($result: any) => {
        return $$createType18($result);
    });
}

export function UpdateControllerListener(req: $models.ListenerSpecRequest): $CancellablePromise<$models.ControllerListenerDTO> {
    return $Call.ByID(3952650828, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdatePivotListener(req: $models.ListenerSpecRequest): $CancellablePromise<$models.PivotListenerDTO> {
    return $Call.ByID(2010392536, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * UpdateSleep 调整 sleep 配置。
 */
export function UpdateSleep(req: $models.UpdateSleepRequest): $CancellablePromise<void> {
    return $Call.ByID(2821179327, req);
}

export function UploadRemoteFile(req: $models.UploadRemoteFileRequest): $CancellablePromise<$models.UploadRemoteFileResult> {
    return $Call.ByID(1083847300, req).then(($result: any) => {
        return $$createType29($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CollectRemoteFileResult.createFrom;
const $$createType1 = $models.ConnectResult.createFrom;
const $$createType2 = $models.ControllerListenerDTO.createFrom;
const $$createType3 = $models.PivotListenerDTO.createFrom;
const $$createType4 = $models.EnqueueDTNResult.createFrom;
const $$createType5 = $models.ExportLootResult.createFrom;
const $$createType6 = $models.ConnectionStatus.createFrom;
const $$createType7 = $models.MetricsDTO.createFrom;
const $$createType8 = $models.SessionDiagnosticsDTO.createFrom;
const $$createType9 = $models.Snapshot.createFrom;
const $$createType10 = $Create.Array($$createType2);
const $$createType11 = $models.ListLootResult.createFrom;
const $$createType12 = $Create.Array($$createType3);
const $$createType13 = $models.RecentConnectionDTO.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.RemoteFileListingDTO.createFrom;
const $$createType16 = $models.SupplementalEventDTO.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $models.SessionActionResult.createFrom;
const $$createType19 = $models.PruneOfflineResult.createFrom;
const $$createType20 = kelpie$0.Event.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $models.StartBackwardProxyResult.createFrom;
const $$createType23 = $models.StartForwardProxyResult.createFrom;
const $$createType24 = $models.StreamHandleDTO.createFrom;
const $$createType25 = $models.StopBackwardProxyResult.createFrom;
const $$createType26 = $models.StopForwardProxyResult.createFrom;
const $$createType27 = $models.StreamDiagDTO.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $models.UploadRemoteFileResult.createFrom;
