// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export class CloseInteractiveStreamRequest {
    "handleId": string;
    "reason"?: string;

    /** Creates a new CloseInteractiveStreamRequest instance. */
    constructor($$source: Partial<CloseInteractiveStreamRequest> = {}) {
        if (!("handleId" in $$source)) {
            this["handleId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseInteractiveStreamRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CloseInteractiveStreamRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseInteractiveStreamRequest($$parsedSource as Partial<CloseInteractiveStreamRequest>);
    }
}

export class CloseStreamByIDRequest {
    "streamId": number;
    "reason"?: string;

    /** Creates a new CloseStreamByIDRequest instance. */
    constructor($$source: Partial<CloseStreamByIDRequest> = {}) {
        if (!("streamId" in $$source)) {
            this["streamId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseStreamByIDRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CloseStreamByIDRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseStreamByIDRequest($$parsedSource as Partial<CloseStreamByIDRequest>);
    }
}

export class CollectRemoteFileRequest {
    "target": string;
    "remotePath": string;
    "tags"?: string[];

    /** Creates a new CollectRemoteFileRequest instance. */
    constructor($$source: Partial<CollectRemoteFileRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("remotePath" in $$source)) {
            this["remotePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectRemoteFileRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CollectRemoteFileRequest {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new CollectRemoteFileRequest($$parsedSource as Partial<CollectRemoteFileRequest>);
    }
}

export class CollectRemoteFileResult {
    "item": LootItemDTO;

    /** Creates a new CollectRemoteFileResult instance. */
    constructor($$source: Partial<CollectRemoteFileResult> = {}) {
        if (!("item" in $$source)) {
            this["item"] = (new LootItemDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectRemoteFileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CollectRemoteFileResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField0_0($$parsedSource["item"]);
        }
        return new CollectRemoteFileResult($$parsedSource as Partial<CollectRemoteFileResult>);
    }
}

/**
 * ConnectRequest 是前端发起连接时的参数。
 */
export class ConnectRequest {
    "endpoint": string;
    "token": string;
    "useTLS": boolean;
    "serverName"?: string;

    /**
     * Remember 为 true 时持久化到 recent connections；token 字段不会落盘以防泄露。
     */
    "remember": boolean;

    /**
     * Label 可选的连接别名，用于 UI 列表显示。
     */
    "label"?: string;

    /**
     * ForceAccept 在 PhaseAwaitingTrust 下由 UI 传回，表示用户已信任该指纹。
     */
    "forceAccept": boolean;

    /** Creates a new ConnectRequest instance. */
    constructor($$source: Partial<ConnectRequest> = {}) {
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("useTLS" in $$source)) {
            this["useTLS"] = false;
        }
        if (!("remember" in $$source)) {
            this["remember"] = false;
        }
        if (!("forceAccept" in $$source)) {
            this["forceAccept"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectRequest($$parsedSource as Partial<ConnectRequest>);
    }
}

/**
 * ConnectResult 反映一次 Connect 调用的结果。
 */
export class ConnectResult {
    "phase": ConnectionPhase;

    /**
     * PendingFingerprint 在 PhaseAwaitingTrust 时非空，前端应展示该指纹并等待用户决定。
     */
    "pendingFingerprint"?: string;

    /**
     * MismatchExpected 在本地指纹与服务端不匹配时非空，前端应严格提示"可能是中间人"。
     */
    "mismatchExpected"?: string;

    /**
     * Endpoint 为实际使用的端点（便于前端做回显）。
     */
    "endpoint"?: string;

    /**
     * Message 附加信息（如错误摘要），仅用于 UI 展示。
     */
    "message"?: string;

    /**
     * Status 汇总当前连接状态。
     */
    "status"?: ConnectionStatus | null;

    /** Creates a new ConnectResult instance. */
    constructor($$source: Partial<ConnectResult> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = ConnectionPhase.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectResult {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField5_0($$parsedSource["status"]);
        }
        return new ConnectResult($$parsedSource as Partial<ConnectResult>);
    }
}

/**
 * ConnectionPhase 描述客户端连接状态机的阶段。
 */
export enum ConnectionPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PhaseDisconnected = "disconnected",

    /**
     * PhaseAwaitingTrust 表示握手拿到了证书，但指纹未被用户信任，需要前端确认后再重试。
     */
    PhaseAwaitingTrust = "awaiting-trust",
    PhaseConnecting = "connecting",
    PhaseConnected = "connected",
};

/**
 * ConnectionStatus 供前端轮询/刷新，描述连接当前态。
 */
export class ConnectionStatus {
    "phase": ConnectionPhase;
    "endpoint"?: string;
    "useTLS": boolean;
    "fingerprint"?: string;
    "connectedAt"?: time$0.Time;
    "error"?: string;

    /** Creates a new ConnectionStatus instance. */
    constructor($$source: Partial<ConnectionStatus> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = ConnectionPhase.$zero;
        }
        if (!("useTLS" in $$source)) {
            this["useTLS"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStatus($$parsedSource as Partial<ConnectionStatus>);
    }
}

export class ControllerListenerDTO {
    "listenerId": string;
    "protocol": string;
    "bind": string;
    "status": string;
    "lastError"?: string;
    "createdAt"?: string;
    "updatedAt"?: string;

    /** Creates a new ControllerListenerDTO instance. */
    constructor($$source: Partial<ControllerListenerDTO> = {}) {
        if (!("listenerId" in $$source)) {
            this["listenerId"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("bind" in $$source)) {
            this["bind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControllerListenerDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ControllerListenerDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ControllerListenerDTO($$parsedSource as Partial<ControllerListenerDTO>);
    }
}

/**
 * DTNMetricsDTO 描述 DTN 队列指标。
 */
export class DTNMetricsDTO {
    "enqueued": number;
    "delivered": number;
    "failed": number;
    "retried": number;
    "global": {"total": number, "ready": number, "held": number, "capacity": number, "highWatermark": number, "averageWait": string, "droppedTotal": number, "expiredTotal": number};

    /** Creates a new DTNMetricsDTO instance. */
    constructor($$source: Partial<DTNMetricsDTO> = {}) {
        if (!("enqueued" in $$source)) {
            this["enqueued"] = 0;
        }
        if (!("delivered" in $$source)) {
            this["delivered"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("retried" in $$source)) {
            this["retried"] = 0;
        }
        if (!("global" in $$source)) {
            this["global"] = {"total": 0, "ready": 0, "held": 0, "capacity": 0, "highWatermark": 0, "averageWait": "", "droppedTotal": 0, "expiredTotal": 0};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DTNMetricsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DTNMetricsDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DTNMetricsDTO($$parsedSource as Partial<DTNMetricsDTO>);
    }
}

/**
 * EdgeSummary 拓扑边的 UI 投影。
 */
export class EdgeSummary {
    "parentUuid": string;
    "childUuid": string;
    "supplemental": boolean;

    /** Creates a new EdgeSummary instance. */
    constructor($$source: Partial<EdgeSummary> = {}) {
        if (!("parentUuid" in $$source)) {
            this["parentUuid"] = "";
        }
        if (!("childUuid" in $$source)) {
            this["childUuid"] = "";
        }
        if (!("supplemental" in $$source)) {
            this["supplemental"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EdgeSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): EdgeSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EdgeSummary($$parsedSource as Partial<EdgeSummary>);
    }
}

/**
 * EnqueueDTNRequest 答辩控制台发一条 DTN payload 的参数。
 */
export class EnqueueDTNRequest {
    "target": string;
    "payload": string;

    /**
     * Priority ∈ {"low","normal","high"}，默认 normal。
     */
    "priority": string;
    "ttlSeconds": number;

    /** Creates a new EnqueueDTNRequest instance. */
    constructor($$source: Partial<EnqueueDTNRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }
        if (!("ttlSeconds" in $$source)) {
            this["ttlSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnqueueDTNRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): EnqueueDTNRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnqueueDTNRequest($$parsedSource as Partial<EnqueueDTNRequest>);
    }
}

/**
 * EnqueueDTNResult 返回 DTN 入队结果。
 */
export class EnqueueDTNResult {
    "bundleId": string;
    "enqueuedAt": time$0.Time;

    /** Creates a new EnqueueDTNResult instance. */
    constructor($$source: Partial<EnqueueDTNResult> = {}) {
        if (!("bundleId" in $$source)) {
            this["bundleId"] = "";
        }
        if (!("enqueuedAt" in $$source)) {
            this["enqueuedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnqueueDTNResult instance from a string or object.
     */
    static createFrom($$source: any = {}): EnqueueDTNResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnqueueDTNResult($$parsedSource as Partial<EnqueueDTNResult>);
    }
}

export class ExportLootRequest {
    "lootId": string;
    "localPath"?: string;

    /** Creates a new ExportLootRequest instance. */
    constructor($$source: Partial<ExportLootRequest> = {}) {
        if (!("lootId" in $$source)) {
            this["lootId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportLootRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportLootRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportLootRequest($$parsedSource as Partial<ExportLootRequest>);
    }
}

export class ExportLootResult {
    "item": LootItemDTO;
    "localPath": string;
    "bytes": number;

    /** Creates a new ExportLootResult instance. */
    constructor($$source: Partial<ExportLootResult> = {}) {
        if (!("item" in $$source)) {
            this["item"] = (new LootItemDTO());
        }
        if (!("localPath" in $$source)) {
            this["localPath"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportLootResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportLootResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField0_0($$parsedSource["item"]);
        }
        return new ExportLootResult($$parsedSource as Partial<ExportLootResult>);
    }
}

export class ListLootRequest {
    "target"?: string;
    "limit"?: number;

    /** Creates a new ListLootRequest instance. */
    constructor($$source: Partial<ListLootRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListLootRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListLootRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListLootRequest($$parsedSource as Partial<ListLootRequest>);
    }
}

export class ListLootResult {
    "items": LootItemDTO[];

    /** Creates a new ListLootResult instance. */
    constructor($$source: Partial<ListLootResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListLootResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ListLootResult {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new ListLootResult($$parsedSource as Partial<ListLootResult>);
    }
}

export class ListPivotListenersRequest {
    "target"?: string;

    /** Creates a new ListPivotListenersRequest instance. */
    constructor($$source: Partial<ListPivotListenersRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListPivotListenersRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListPivotListenersRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListPivotListenersRequest($$parsedSource as Partial<ListPivotListenersRequest>);
    }
}

export class ListRemoteFilesRequest {
    "target": string;
    "path"?: string;

    /** Creates a new ListRemoteFilesRequest instance. */
    constructor($$source: Partial<ListRemoteFilesRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListRemoteFilesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListRemoteFilesRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListRemoteFilesRequest($$parsedSource as Partial<ListRemoteFilesRequest>);
    }
}

export class ListenerSpecRequest {
    "listenerId"?: string;
    "target"?: string;
    "protocol"?: string;
    "bind"?: string;
    "mode"?: string;
    "desiredStatus"?: string;
    "includeSpec"?: boolean;

    /** Creates a new ListenerSpecRequest instance. */
    constructor($$source: Partial<ListenerSpecRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListenerSpecRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListenerSpecRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListenerSpecRequest($$parsedSource as Partial<ListenerSpecRequest>);
    }
}

export class LootItemDTO {
    "lootId": string;
    "targetUuid"?: string;
    "operator"?: string;
    "category"?: string;
    "name"?: string;
    "storageRef"?: string;
    "originPath"?: string;
    "hash"?: string;
    "size"?: number;
    "mime"?: string;
    "metadata"?: { [_ in string]?: string };
    "tags"?: string[];
    "createdAt"?: string;

    /** Creates a new LootItemDTO instance. */
    constructor($$source: Partial<LootItemDTO> = {}) {
        if (!("lootId" in $$source)) {
            this["lootId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LootItemDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LootItemDTO {
        const $$createField10_0 = $$createType5;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField10_0($$parsedSource["metadata"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField11_0($$parsedSource["tags"]);
        }
        return new LootItemDTO($$parsedSource as Partial<LootItemDTO>);
    }
}

/**
 * MetricsDTO 聚合指标（DTN/router/reconnect + 补链）。
 */
export class MetricsDTO {
    "dtn": DTNMetricsDTO;
    "reconnect": ReconnectMetricsDTO;
    "supplemental": SupplementalSnapshot;
    "capturedAt": time$0.Time;

    /** Creates a new MetricsDTO instance. */
    constructor($$source: Partial<MetricsDTO> = {}) {
        if (!("dtn" in $$source)) {
            this["dtn"] = (new DTNMetricsDTO());
        }
        if (!("reconnect" in $$source)) {
            this["reconnect"] = (new ReconnectMetricsDTO());
        }
        if (!("supplemental" in $$source)) {
            this["supplemental"] = (new SupplementalSnapshot());
        }
        if (!("capturedAt" in $$source)) {
            this["capturedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): MetricsDTO {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dtn" in $$parsedSource) {
            $$parsedSource["dtn"] = $$createField0_0($$parsedSource["dtn"]);
        }
        if ("reconnect" in $$parsedSource) {
            $$parsedSource["reconnect"] = $$createField1_0($$parsedSource["reconnect"]);
        }
        if ("supplemental" in $$parsedSource) {
            $$parsedSource["supplemental"] = $$createField2_0($$parsedSource["supplemental"]);
        }
        return new MetricsDTO($$parsedSource as Partial<MetricsDTO>);
    }
}

/**
 * NodeSummary 拓扑节点的 UI 投影。
 */
export class NodeSummary {
    "uuid": string;
    "alias"?: string;
    "parentUuid"?: string;
    "status"?: string;
    "network"?: string;
    "sleep"?: string;
    "memo"?: string;
    "depth": number;
    "tags"?: string[];
    "activeStreams": number;
    "workProfile"?: string;

    /** Creates a new NodeSummary instance. */
    constructor($$source: Partial<NodeSummary> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("depth" in $$source)) {
            this["depth"] = 0;
        }
        if (!("activeStreams" in $$source)) {
            this["activeStreams"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeSummary {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new NodeSummary($$parsedSource as Partial<NodeSummary>);
    }
}

/**
 * PivotListenerDTO 节点上的 pivot 监听器。
 */
export class PivotListenerDTO {
    "listenerId": string;
    "targetUuid"?: string;
    "route"?: string;
    "protocol": string;
    "bind": string;
    "status": string;
    "mode": string;
    "lastError"?: string;
    "metadata"?: { [_ in string]?: string };
    "createdAt"?: string;
    "updatedAt"?: string;

    /** Creates a new PivotListenerDTO instance. */
    constructor($$source: Partial<PivotListenerDTO> = {}) {
        if (!("listenerId" in $$source)) {
            this["listenerId"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("bind" in $$source)) {
            this["bind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PivotListenerDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PivotListenerDTO {
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField8_0($$parsedSource["metadata"]);
        }
        return new PivotListenerDTO($$parsedSource as Partial<PivotListenerDTO>);
    }
}

/**
 * PruneOfflineResult 返回清理结果。
 */
export class PruneOfflineResult {
    "removed": number;

    /** Creates a new PruneOfflineResult instance. */
    constructor($$source: Partial<PruneOfflineResult> = {}) {
        if (!("removed" in $$source)) {
            this["removed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PruneOfflineResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PruneOfflineResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PruneOfflineResult($$parsedSource as Partial<PruneOfflineResult>);
    }
}

/**
 * RecentConnectionDTO 是持久化的连接记录在前端的投影。
 */
export class RecentConnectionDTO {
    "id": string;
    "label": string;
    "endpoint": string;
    "useTLS": boolean;
    "serverName"?: string;
    "fingerprint"?: string;
    "lastUsedAt": time$0.Time;

    /** Creates a new RecentConnectionDTO instance. */
    constructor($$source: Partial<RecentConnectionDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("useTLS" in $$source)) {
            this["useTLS"] = false;
        }
        if (!("lastUsedAt" in $$source)) {
            this["lastUsedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentConnectionDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentConnectionDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentConnectionDTO($$parsedSource as Partial<RecentConnectionDTO>);
    }
}

/**
 * ReconnectMetricsDTO 描述上游重连统计。
 */
export class ReconnectMetricsDTO {
    "attempts": number;
    "success": number;
    "failures": number;
    "lastError"?: string;

    /** Creates a new ReconnectMetricsDTO instance. */
    constructor($$source: Partial<ReconnectMetricsDTO> = {}) {
        if (!("attempts" in $$source)) {
            this["attempts"] = 0;
        }
        if (!("success" in $$source)) {
            this["success"] = 0;
        }
        if (!("failures" in $$source)) {
            this["failures"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReconnectMetricsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ReconnectMetricsDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReconnectMetricsDTO($$parsedSource as Partial<ReconnectMetricsDTO>);
    }
}

export class RemoteFileEntryDTO {
    "name": string;
    "path": string;
    "isDir": boolean;
    "isDrive"?: boolean;
    "isSymlink"?: boolean;
    "size"?: number;
    "mode"?: string;
    "modifiedAt"?: string;
    "hidden"?: boolean;

    /** Creates a new RemoteFileEntryDTO instance. */
    constructor($$source: Partial<RemoteFileEntryDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteFileEntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteFileEntryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteFileEntryDTO($$parsedSource as Partial<RemoteFileEntryDTO>);
    }
}

export class RemoteFileListingDTO {
    "requestedPath"?: string;
    "resolvedPath"?: string;
    "displayPath"?: string;
    "rootPath"?: string;
    "parentPath"?: string;
    "canGoUp": boolean;
    "virtualRoot": boolean;
    "entries"?: RemoteFileEntryDTO[];

    /** Creates a new RemoteFileListingDTO instance. */
    constructor($$source: Partial<RemoteFileListingDTO> = {}) {
        if (!("canGoUp" in $$source)) {
            this["canGoUp"] = false;
        }
        if (!("virtualRoot" in $$source)) {
            this["virtualRoot"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteFileListingDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteFileListingDTO {
        const $$createField7_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField7_0($$parsedSource["entries"]);
        }
        return new RemoteFileListingDTO($$parsedSource as Partial<RemoteFileListingDTO>);
    }
}

export class SessionActionRequest {
    "target": string;
    "action"?: string;
    "force"?: boolean;
    "reason"?: string;

    /** Creates a new SessionActionRequest instance. */
    constructor($$source: Partial<SessionActionRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionActionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionActionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionActionRequest($$parsedSource as Partial<SessionActionRequest>);
    }
}

export class SessionActionResult {
    "session"?: SessionSummary;
    "accepted"?: boolean;
    "terminated"?: boolean;
    "message"?: string;

    /** Creates a new SessionActionResult instance. */
    constructor($$source: Partial<SessionActionResult> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionActionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionActionResult {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new SessionActionResult($$parsedSource as Partial<SessionActionResult>);
    }
}

export class SessionDiagnosticsDTO {
    "session": SessionSummary;
    "metrics"?: SessionMetricDTO[];
    "issues"?: SessionIssueDTO[];
    "processes"?: SessionProcessDTO[];

    /** Creates a new SessionDiagnosticsDTO instance. */
    constructor($$source: Partial<SessionDiagnosticsDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionDiagnosticsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionDiagnosticsDTO {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType13;
        const $$createField2_0 = $$createType15;
        const $$createField3_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField1_0($$parsedSource["metrics"]);
        }
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField2_0($$parsedSource["issues"]);
        }
        if ("processes" in $$parsedSource) {
            $$parsedSource["processes"] = $$createField3_0($$parsedSource["processes"]);
        }
        return new SessionDiagnosticsDTO($$parsedSource as Partial<SessionDiagnosticsDTO>);
    }
}

export class SessionIssueDTO {
    "code": string;
    "message": string;
    "detail"?: string;

    /** Creates a new SessionIssueDTO instance. */
    constructor($$source: Partial<SessionIssueDTO> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionIssueDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionIssueDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionIssueDTO($$parsedSource as Partial<SessionIssueDTO>);
    }
}

export class SessionMetricDTO {
    "name": string;
    "value": string;

    /** Creates a new SessionMetricDTO instance. */
    constructor($$source: Partial<SessionMetricDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionMetricDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionMetricDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionMetricDTO($$parsedSource as Partial<SessionMetricDTO>);
    }
}

export class SessionProcessDTO {
    "pid": string;
    "name": string;
    "user"?: string;
    "status"?: string;
    "path"?: string;
    "startedAt"?: string;

    /** Creates a new SessionProcessDTO instance. */
    constructor($$source: Partial<SessionProcessDTO> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionProcessDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionProcessDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionProcessDTO($$parsedSource as Partial<SessionProcessDTO>);
    }
}

/**
 * SessionSummary 会话的 UI 投影。
 */
export class SessionSummary {
    "targetUuid": string;
    "status": string;
    "active": boolean;
    "connected": boolean;
    "remoteAddr"?: string;
    "upstream"?: string;
    "downstream"?: string;
    "networkId"?: string;
    "lastSeen"?: string;
    "lastError"?: string;
    "sleepSeconds"?: number | null;
    "workSeconds"?: number | null;
    "jitter"?: number | null;

    /** Creates a new SessionSummary instance. */
    constructor($$source: Partial<SessionSummary> = {}) {
        if (!("targetUuid" in $$source)) {
            this["targetUuid"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionSummary($$parsedSource as Partial<SessionSummary>);
    }
}

/**
 * SleepProfileDTO 节点 sleep 快照。
 */
export class SleepProfileDTO {
    "targetUuid": string;
    "sleepSeconds"?: number | null;
    "workSeconds"?: number | null;
    "jitter"?: number | null;
    "profile"?: string;
    "lastUpdated"?: string;
    "nextWakeAt"?: string;
    "status"?: string;

    /** Creates a new SleepProfileDTO instance. */
    constructor($$source: Partial<SleepProfileDTO> = {}) {
        if (!("targetUuid" in $$source)) {
            this["targetUuid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SleepProfileDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SleepProfileDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SleepProfileDTO($$parsedSource as Partial<SleepProfileDTO>);
    }
}

/**
 * Snapshot 是 UI 初始化需要的一整份拓扑。
 */
export class Snapshot {
    "nodes": NodeSummary[];
    "edges": EdgeSummary[];
    "streams": StreamDiagDTO[];
    "sessions": SessionSummary[];
    "pivotListeners"?: PivotListenerDTO[];
    "controllerListeners"?: ControllerListenerDTO[];
    "sleepProfiles"?: SleepProfileDTO[];
    "fetchedAt": time$0.Time;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }
        if (!("streams" in $$source)) {
            this["streams"] = [];
        }
        if (!("sessions" in $$source)) {
            this["sessions"] = [];
        }
        if (!("fetchedAt" in $$source)) {
            this["fetchedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField0_0 = $$createType19;
        const $$createField1_0 = $$createType21;
        const $$createField2_0 = $$createType23;
        const $$createField3_0 = $$createType24;
        const $$createField4_0 = $$createType26;
        const $$createField5_0 = $$createType28;
        const $$createField6_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField1_0($$parsedSource["edges"]);
        }
        if ("streams" in $$parsedSource) {
            $$parsedSource["streams"] = $$createField2_0($$parsedSource["streams"]);
        }
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField3_0($$parsedSource["sessions"]);
        }
        if ("pivotListeners" in $$parsedSource) {
            $$parsedSource["pivotListeners"] = $$createField4_0($$parsedSource["pivotListeners"]);
        }
        if ("controllerListeners" in $$parsedSource) {
            $$parsedSource["controllerListeners"] = $$createField5_0($$parsedSource["controllerListeners"]);
        }
        if ("sleepProfiles" in $$parsedSource) {
            $$parsedSource["sleepProfiles"] = $$createField6_0($$parsedSource["sleepProfiles"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

export class StartBackwardProxyRequest {
    "target": string;
    "remotePort": string;
    "localPort": string;

    /** Creates a new StartBackwardProxyRequest instance. */
    constructor($$source: Partial<StartBackwardProxyRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartBackwardProxyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartBackwardProxyRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartBackwardProxyRequest($$parsedSource as Partial<StartBackwardProxyRequest>);
    }
}

export class StartBackwardProxyResult {
    "handle": StreamHandleDTO;
    "proxyId": string;
    "kind"?: string;
    "remotePort": string;
    "localPort": string;

    /** Creates a new StartBackwardProxyResult instance. */
    constructor($$source: Partial<StartBackwardProxyResult> = {}) {
        if (!("handle" in $$source)) {
            this["handle"] = (new StreamHandleDTO());
        }
        if (!("proxyId" in $$source)) {
            this["proxyId"] = "";
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartBackwardProxyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StartBackwardProxyResult {
        const $$createField0_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("handle" in $$parsedSource) {
            $$parsedSource["handle"] = $$createField0_0($$parsedSource["handle"]);
        }
        return new StartBackwardProxyResult($$parsedSource as Partial<StartBackwardProxyResult>);
    }
}

export class StartForwardProxyRequest {
    "target": string;
    "localBind": string;
    "remoteAddr": string;

    /** Creates a new StartForwardProxyRequest instance. */
    constructor($$source: Partial<StartForwardProxyRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("localBind" in $$source)) {
            this["localBind"] = "";
        }
        if (!("remoteAddr" in $$source)) {
            this["remoteAddr"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartForwardProxyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartForwardProxyRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartForwardProxyRequest($$parsedSource as Partial<StartForwardProxyRequest>);
    }
}

export class StartForwardProxyResult {
    "handle": StreamHandleDTO;
    "proxyId": string;
    "kind"?: string;
    "bind": string;
    "remoteAddr": string;

    /** Creates a new StartForwardProxyResult instance. */
    constructor($$source: Partial<StartForwardProxyResult> = {}) {
        if (!("handle" in $$source)) {
            this["handle"] = (new StreamHandleDTO());
        }
        if (!("proxyId" in $$source)) {
            this["proxyId"] = "";
        }
        if (!("bind" in $$source)) {
            this["bind"] = "";
        }
        if (!("remoteAddr" in $$source)) {
            this["remoteAddr"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartForwardProxyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StartForwardProxyResult {
        const $$createField0_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("handle" in $$parsedSource) {
            $$parsedSource["handle"] = $$createField0_0($$parsedSource["handle"]);
        }
        return new StartForwardProxyResult($$parsedSource as Partial<StartForwardProxyResult>);
    }
}

export class StartShellRequest {
    "target": string;
    "mode"?: string;
    "resumeSessionId"?: string;

    /** Creates a new StartShellRequest instance. */
    constructor($$source: Partial<StartShellRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartShellRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartShellRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartShellRequest($$parsedSource as Partial<StartShellRequest>);
    }
}

export class StartSocksProxyRequest {
    "target": string;
    "auth"?: string;
    "username"?: string;
    "password"?: string;

    /** Creates a new StartSocksProxyRequest instance. */
    constructor($$source: Partial<StartSocksProxyRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartSocksProxyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartSocksProxyRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartSocksProxyRequest($$parsedSource as Partial<StartSocksProxyRequest>);
    }
}

export class StartSshSessionRequest {
    "target": string;
    "serverAddr": string;
    "username": string;
    "password": string;

    /** Creates a new StartSshSessionRequest instance. */
    constructor($$source: Partial<StartSshSessionRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("serverAddr" in $$source)) {
            this["serverAddr"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartSshSessionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartSshSessionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartSshSessionRequest($$parsedSource as Partial<StartSshSessionRequest>);
    }
}

export class StartSshTunnelRequest {
    "target": string;
    "serverAddr": string;
    "agentPort": string;
    "authMethod"?: string;
    "username": string;
    "password"?: string;
    "privateKey"?: string;

    /** Creates a new StartSshTunnelRequest instance. */
    constructor($$source: Partial<StartSshTunnelRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("serverAddr" in $$source)) {
            this["serverAddr"] = "";
        }
        if (!("agentPort" in $$source)) {
            this["agentPort"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartSshTunnelRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartSshTunnelRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartSshTunnelRequest($$parsedSource as Partial<StartSshTunnelRequest>);
    }
}

export class StopBackwardProxyRequest {
    "target": string;
    "proxyId": string;

    /** Creates a new StopBackwardProxyRequest instance. */
    constructor($$source: Partial<StopBackwardProxyRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("proxyId" in $$source)) {
            this["proxyId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StopBackwardProxyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StopBackwardProxyRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StopBackwardProxyRequest($$parsedSource as Partial<StopBackwardProxyRequest>);
    }
}

export class StopBackwardProxyResult {
    "stopped": number;

    /** Creates a new StopBackwardProxyResult instance. */
    constructor($$source: Partial<StopBackwardProxyResult> = {}) {
        if (!("stopped" in $$source)) {
            this["stopped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StopBackwardProxyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StopBackwardProxyResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StopBackwardProxyResult($$parsedSource as Partial<StopBackwardProxyResult>);
    }
}

export class StopForwardProxyRequest {
    "target": string;
    "proxyId": string;

    /** Creates a new StopForwardProxyRequest instance. */
    constructor($$source: Partial<StopForwardProxyRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("proxyId" in $$source)) {
            this["proxyId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StopForwardProxyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StopForwardProxyRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StopForwardProxyRequest($$parsedSource as Partial<StopForwardProxyRequest>);
    }
}

export class StopForwardProxyResult {
    "stopped": number;

    /** Creates a new StopForwardProxyResult instance. */
    constructor($$source: Partial<StopForwardProxyResult> = {}) {
        if (!("stopped" in $$source)) {
            this["stopped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StopForwardProxyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StopForwardProxyResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StopForwardProxyResult($$parsedSource as Partial<StopForwardProxyResult>);
    }
}

export class StreamDataRequest {
    "handleId": string;
    "data": string;

    /** Creates a new StreamDataRequest instance. */
    constructor($$source: Partial<StreamDataRequest> = {}) {
        if (!("handleId" in $$source)) {
            this["handleId"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamDataRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamDataRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamDataRequest($$parsedSource as Partial<StreamDataRequest>);
    }
}

/**
 * StreamDiagDTO 用于节点详情的"活跃流"小视图。
 */
export class StreamDiagDTO {
    "streamId": number;
    "targetUuid": string;
    "kind": string;
    "outbound": boolean;
    "pending": number;
    "inFlight": number;
    "window": number;
    "seq": number;
    "ack": number;
    "rto": string;
    "lastActivity": string;
    "sessionId": string;

    /** Creates a new StreamDiagDTO instance. */
    constructor($$source: Partial<StreamDiagDTO> = {}) {
        if (!("streamId" in $$source)) {
            this["streamId"] = 0;
        }
        if (!("targetUuid" in $$source)) {
            this["targetUuid"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("outbound" in $$source)) {
            this["outbound"] = false;
        }
        if (!("pending" in $$source)) {
            this["pending"] = 0;
        }
        if (!("inFlight" in $$source)) {
            this["inFlight"] = 0;
        }
        if (!("window" in $$source)) {
            this["window"] = 0;
        }
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("ack" in $$source)) {
            this["ack"] = 0;
        }
        if (!("rto" in $$source)) {
            this["rto"] = "";
        }
        if (!("lastActivity" in $$source)) {
            this["lastActivity"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamDiagDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamDiagDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamDiagDTO($$parsedSource as Partial<StreamDiagDTO>);
    }
}

export class StreamHandleDTO {
    "handleId": string;
    "targetUuid": string;
    "sessionId": string;
    "kind": string;
    "streamId"?: number;
    "options"?: { [_ in string]?: string };
    "status": string;

    /** Creates a new StreamHandleDTO instance. */
    constructor($$source: Partial<StreamHandleDTO> = {}) {
        if (!("handleId" in $$source)) {
            this["handleId"] = "";
        }
        if (!("targetUuid" in $$source)) {
            this["targetUuid"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamHandleDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamHandleDTO {
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        return new StreamHandleDTO($$parsedSource as Partial<StreamHandleDTO>);
    }
}

export class StreamPingRequest {
    "target": string;
    "count": number;
    "payloadSize": number;

    /** Creates a new StreamPingRequest instance. */
    constructor($$source: Partial<StreamPingRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("payloadSize" in $$source)) {
            this["payloadSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamPingRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamPingRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamPingRequest($$parsedSource as Partial<StreamPingRequest>);
    }
}

export class StreamResizeRequest {
    "handleId": string;
    "rows": number;
    "cols": number;

    /** Creates a new StreamResizeRequest instance. */
    constructor($$source: Partial<StreamResizeRequest> = {}) {
        if (!("handleId" in $$source)) {
            this["handleId"] = "";
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamResizeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamResizeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamResizeRequest($$parsedSource as Partial<StreamResizeRequest>);
    }
}

/**
 * SupplementalEventDTO 补链事件的简单投影。
 */
export class SupplementalEventDTO {
    "seq": number;
    "kind": string;
    "action": string;
    "source"?: string;
    "target"?: string;
    "detail"?: string;
    "timestamp": string;

    /** Creates a new SupplementalEventDTO instance. */
    constructor($$source: Partial<SupplementalEventDTO> = {}) {
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupplementalEventDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SupplementalEventDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SupplementalEventDTO($$parsedSource as Partial<SupplementalEventDTO>);
    }
}

/**
 * SupplementalSnapshot 补链调度器综合状态。
 */
export class SupplementalSnapshot {
    "enabled": boolean;
    "queueLength": number;
    "pendingActions": number;
    "activeLinks": number;
    "dispatched": number;
    "success": number;
    "failures": number;
    "dropped": number;
    "recycled": number;
    "queueHigh": number;
    "lastFailure"?: string;

    /** Creates a new SupplementalSnapshot instance. */
    constructor($$source: Partial<SupplementalSnapshot> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("queueLength" in $$source)) {
            this["queueLength"] = 0;
        }
        if (!("pendingActions" in $$source)) {
            this["pendingActions"] = 0;
        }
        if (!("activeLinks" in $$source)) {
            this["activeLinks"] = 0;
        }
        if (!("dispatched" in $$source)) {
            this["dispatched"] = 0;
        }
        if (!("success" in $$source)) {
            this["success"] = 0;
        }
        if (!("failures" in $$source)) {
            this["failures"] = 0;
        }
        if (!("dropped" in $$source)) {
            this["dropped"] = 0;
        }
        if (!("recycled" in $$source)) {
            this["recycled"] = 0;
        }
        if (!("queueHigh" in $$source)) {
            this["queueHigh"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupplementalSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): SupplementalSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SupplementalSnapshot($$parsedSource as Partial<SupplementalSnapshot>);
    }
}

/**
 * UpdateSleepRequest 调整节点 sleep 配置。
 * 为 nil 的字段不会被下发。
 */
export class UpdateSleepRequest {
    "target": string;
    "sleepSeconds"?: number | null;
    "workSeconds"?: number | null;
    "jitter"?: number | null;

    /** Creates a new UpdateSleepRequest instance. */
    constructor($$source: Partial<UpdateSleepRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateSleepRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateSleepRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateSleepRequest($$parsedSource as Partial<UpdateSleepRequest>);
    }
}

export class UploadRemoteFileRequest {
    "target": string;
    "localPath": string;
    "remotePath": string;

    /** Creates a new UploadRemoteFileRequest instance. */
    constructor($$source: Partial<UploadRemoteFileRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("localPath" in $$source)) {
            this["localPath"] = "";
        }
        if (!("remotePath" in $$source)) {
            this["remotePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadRemoteFileRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadRemoteFileRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadRemoteFileRequest($$parsedSource as Partial<UploadRemoteFileRequest>);
    }
}

export class UploadRemoteFileResult {
    "remotePath": string;
    "size"?: number;
    "sha256"?: string;
    "mime"?: string;
    "message"?: string;

    /** Creates a new UploadRemoteFileResult instance. */
    constructor($$source: Partial<UploadRemoteFileResult> = {}) {
        if (!("remotePath" in $$source)) {
            this["remotePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadRemoteFileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadRemoteFileResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadRemoteFileResult($$parsedSource as Partial<UploadRemoteFileResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = LootItemDTO.createFrom;
const $$createType2 = ConnectionStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType1);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = DTNMetricsDTO.createFrom;
const $$createType7 = ReconnectMetricsDTO.createFrom;
const $$createType8 = SupplementalSnapshot.createFrom;
const $$createType9 = RemoteFileEntryDTO.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = SessionSummary.createFrom;
const $$createType12 = SessionMetricDTO.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = SessionIssueDTO.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = SessionProcessDTO.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = NodeSummary.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = EdgeSummary.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = StreamDiagDTO.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = $Create.Array($$createType11);
const $$createType25 = PivotListenerDTO.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = ControllerListenerDTO.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = SleepProfileDTO.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = StreamHandleDTO.createFrom;
